import type { ActivityDefinition } from '@/domain/activity/schema';
import { palette } from '@/theme';

/** Grade 1 (Philippines) numeracy: counting to 20, sorting by attribute, comparing sets. */
export const countingActivities: ActivityDefinition[] = [
  {
    id: 'act_count_sea',
    kind: 'COUNTING',
    islandId: 'numbers',
    title: 'Count the Sea Friends',
    icon: 'fish',
    color: palette.aqua,
    voiceIntro: 'How many sea friends can you count? Tap the right number.',
    instruction: 'Count, then tap the number.',
    reward: { diamonds: 4, stickerId: 'stk_fish' },
    tags: ['counting', 'numbers-1-10'],
    data: {
      kind: 'COUNTING',
      mode: 'count',
      rounds: [
        {
          id: 'r1',
          picture: { icon: 'fish', color: palette.tangerine },
          count: 3,
          choices: [2, 3, 5],
        },
        {
          id: 'r2',
          picture: { icon: 'starfish', color: palette.coral },
          count: 5,
          choices: [4, 5, 6],
        },
        {
          id: 'r3',
          picture: { icon: 'shell', color: palette.blossom },
          count: 2,
          choices: [1, 2, 3],
        },
        { id: 'r4', picture: { icon: 'crab', color: palette.coral }, count: 7, choices: [6, 7, 9] },
        {
          id: 'r5',
          picture: { icon: 'turtle', color: palette.leaf },
          count: 4,
          choices: [3, 4, 5],
        },
        {
          id: 'r6',
          picture: { icon: 'jellyfish', color: palette.sunshine },
          count: 8,
          choices: [7, 8, 10],
        },
      ],
    },
  },
  {
    id: 'act_count_big',
    kind: 'COUNTING',
    islandId: 'numbers',
    title: 'Count to Twenty',
    icon: 'numbers',
    color: palette.sea,
    voiceIntro: 'Big numbers! Count carefully, then tap the number.',
    instruction: 'Count the diamonds, then tap the number.',
    reward: { diamonds: 5, stickerId: 'stk_diamond' },
    tags: ['counting', 'numbers-11-20'],
    data: {
      kind: 'COUNTING',
      mode: 'count',
      rounds: [
        {
          id: 'r1',
          picture: { icon: 'diamond', color: palette.aqua },
          count: 11,
          choices: [10, 11, 12],
        },
        {
          id: 'r2',
          picture: { icon: 'star', color: palette.sunshine },
          count: 14,
          choices: [12, 14, 16],
        },
        {
          id: 'r3',
          picture: { icon: 'heart', color: palette.blossom },
          count: 12,
          choices: [11, 12, 13],
        },
        {
          id: 'r4',
          picture: { icon: 'flower', color: palette.coral },
          count: 17,
          choices: [15, 17, 18],
        },
        {
          id: 'r5',
          picture: { icon: 'leaf', color: palette.leaf },
          count: 20,
          choices: [18, 19, 20],
        },
      ],
    },
  },
  {
    id: 'act_sort_colors',
    kind: 'COUNTING',
    islandId: 'numbers',
    title: 'Sort by Color',
    icon: 'palette',
    color: palette.blossom,
    voiceIntro: 'Tap a shape, then tap the basket with the same color.',
    instruction: 'Tap a shape, then its basket.',
    reward: { diamonds: 4, stickerId: 'stk_palette' },
    tags: ['sorting', 'colors'],
    data: {
      kind: 'COUNTING',
      mode: 'sort',
      rounds: [
        {
          id: 'r1',
          prompt: 'Put the red ones and the blue ones in their baskets.',
          bins: [
            { id: 'red', label: 'Red', color: palette.coral },
            { id: 'blue', label: 'Blue', color: palette.sea },
          ],
          items: [
            { id: 'i1', picture: { icon: 'star', color: palette.coral }, binId: 'red' },
            { id: 'i2', picture: { icon: 'heart', color: palette.sea }, binId: 'blue' },
            { id: 'i3', picture: { icon: 'circle', color: palette.sea }, binId: 'blue' },
            { id: 'i4', picture: { icon: 'square', color: palette.coral }, binId: 'red' },
            { id: 'i5', picture: { icon: 'triangle', color: palette.coral }, binId: 'red' },
            { id: 'i6', picture: { icon: 'diamond', color: palette.sea }, binId: 'blue' },
          ],
        },
        {
          id: 'r2',
          prompt: 'Yellow, green or purple?',
          bins: [
            { id: 'yellow', label: 'Yellow', color: palette.sunshine },
            { id: 'green', label: 'Green', color: palette.leaf },
            { id: 'purple', label: 'Purple', color: palette.lavender },
          ],
          items: [
            { id: 'i1', picture: { icon: 'star', color: palette.sunshine }, binId: 'yellow' },
            { id: 'i2', picture: { icon: 'leaf', color: palette.leaf }, binId: 'green' },
            { id: 'i3', picture: { icon: 'heart', color: palette.lavender }, binId: 'purple' },
            { id: 'i4', picture: { icon: 'circle', color: palette.leaf }, binId: 'green' },
            { id: 'i5', picture: { icon: 'square', color: palette.sunshine }, binId: 'yellow' },
            { id: 'i6', picture: { icon: 'triangle', color: palette.lavender }, binId: 'purple' },
          ],
        },
      ],
    },
  },
  {
    id: 'act_sort_shapes',
    kind: 'COUNTING',
    islandId: 'numbers',
    title: 'Sort by Shape',
    icon: 'triangle',
    color: palette.leaf,
    voiceIntro: 'Circles, squares and triangles! Tap a shape, then tap its basket.',
    instruction: 'Tap a shape, then its basket.',
    reward: { diamonds: 4 },
    tags: ['sorting', 'shapes'],
    data: {
      kind: 'COUNTING',
      mode: 'sort',
      rounds: [
        {
          id: 'r1',
          prompt: 'Circle or square?',
          bins: [
            { id: 'circle', label: 'Circles', picture: { icon: 'circle', color: palette.ink } },
            { id: 'square', label: 'Squares', picture: { icon: 'square', color: palette.ink } },
          ],
          items: [
            { id: 'i1', picture: { icon: 'circle', color: palette.coral }, binId: 'circle' },
            { id: 'i2', picture: { icon: 'square', color: palette.sea }, binId: 'square' },
            { id: 'i3', picture: { icon: 'circle', color: palette.leaf }, binId: 'circle' },
            { id: 'i4', picture: { icon: 'square', color: palette.sunshine }, binId: 'square' },
            { id: 'i5', picture: { icon: 'circle', color: palette.lavender }, binId: 'circle' },
          ],
        },
        {
          id: 'r2',
          prompt: 'Triangle, circle or square?',
          bins: [
            { id: 'tri', label: 'Triangles', picture: { icon: 'triangle', color: palette.ink } },
            { id: 'circle', label: 'Circles', picture: { icon: 'circle', color: palette.ink } },
            { id: 'square', label: 'Squares', picture: { icon: 'square', color: palette.ink } },
          ],
          items: [
            { id: 'i1', picture: { icon: 'triangle', color: palette.coral }, binId: 'tri' },
            { id: 'i2', picture: { icon: 'circle', color: palette.sea }, binId: 'circle' },
            { id: 'i3', picture: { icon: 'square', color: palette.leaf }, binId: 'square' },
            { id: 'i4', picture: { icon: 'triangle', color: palette.sunshine }, binId: 'tri' },
            { id: 'i5', picture: { icon: 'square', color: palette.lavender }, binId: 'square' },
            { id: 'i6', picture: { icon: 'circle', color: palette.tangerine }, binId: 'circle' },
          ],
        },
      ],
    },
  },
  {
    id: 'act_compare_more',
    kind: 'COUNTING',
    islandId: 'numbers',
    title: 'More or Less?',
    icon: 'starfish',
    color: palette.tangerine,
    voiceIntro: 'Which side has more? Tap it! If they are the same, tap Same.',
    instruction: 'Tap the side with more.',
    reward: { diamonds: 4, stickerId: 'stk_starfish' },
    tags: ['comparing', 'numbers'],
    data: {
      kind: 'COUNTING',
      mode: 'compare',
      rounds: [
        {
          id: 'r1',
          prompt: 'Which side has more fish?',
          left: { picture: { icon: 'fish', color: palette.tangerine }, count: 3 },
          right: { picture: { icon: 'fish', color: palette.tangerine }, count: 5 },
          answer: 'right',
        },
        {
          id: 'r2',
          prompt: 'Which side has more stars?',
          left: { picture: { icon: 'star', color: palette.sunshine }, count: 6 },
          right: { picture: { icon: 'star', color: palette.sunshine }, count: 2 },
          answer: 'left',
        },
        {
          id: 'r3',
          prompt: 'Which side has more shells?',
          left: { picture: { icon: 'shell', color: palette.blossom }, count: 4 },
          right: { picture: { icon: 'shell', color: palette.blossom }, count: 4 },
          answer: 'same',
        },
        {
          id: 'r4',
          prompt: 'Which side has more crabs?',
          left: { picture: { icon: 'crab', color: palette.coral }, count: 7 },
          right: { picture: { icon: 'crab', color: palette.coral }, count: 9 },
          answer: 'right',
        },
      ],
    },
  },
];
