import type { ActivityDefinition } from '@/domain/activity/schema';
import { palette } from '@/theme';

/** Free drawing and crafts as activities so they appear on islands and in quests. */
export const creativeActivities: ActivityDefinition[] = [
  {
    id: 'act_draw_free',
    grades: [1, 2, 3, 4, 5, 6],
    subject: 'art',
    kind: 'DRAW',
    islandId: 'art',
    title: 'Draw & Paint',
    icon: 'paintbrush',
    color: palette.sunshine,
    voiceIntro: "Let's draw! Use the brush, crayon and stamps.",
    instruction: 'Draw anything you like, then save it.',
    reward: { diamonds: 3, stickerId: 'stk_heart' },
    tags: ['drawing', 'creative'],
    data: { kind: 'DRAW' },
  },
  {
    id: 'act_draw_fish',
    grades: [1, 2, 3, 4, 5, 6],
    subject: 'art',
    kind: 'DRAW',
    islandId: 'art',
    title: 'Draw a Happy Fish',
    icon: 'fish',
    color: palette.aqua,
    voiceIntro: 'Can you draw a happy fish? Give it a big smile!',
    instruction: 'Draw a happy fish, then save it.',
    reward: { diamonds: 3 },
    tags: ['drawing', 'creative'],
    data: { kind: 'DRAW', idea: 'Draw a happy fish with a big smile.' },
  },
  {
    id: 'act_craft_clay_cup',
    grades: [1, 2, 3],
    subject: 'craft',
    kind: 'CRAFT',
    islandId: 'crafts',
    title: "PJ's Clay Cup",
    icon: 'clay',
    color: palette.tangerine,
    voiceIntro: "Let's make a clay cup, step by step.",
    instruction: 'Follow the steps to make a cup.',
    reward: { diamonds: 6, stickerId: 'stk_shell' },
    tags: ['craft', 'clay'],
    data: { kind: 'CRAFT', craftId: 'crf_clay_cup' },
  },
  {
    id: 'act_craft_paper_crown',
    grades: [1, 2, 3],
    subject: 'craft',
    kind: 'CRAFT',
    islandId: 'crafts',
    title: 'Paper Crown',
    icon: 'crown',
    color: palette.sunshine,
    voiceIntro: "Let's make a paper crown fit for a princess!",
    instruction: 'Follow the steps to make a crown.',
    reward: { diamonds: 6, stickerId: 'stk_crown' },
    tags: ['craft', 'paper'],
    data: { kind: 'CRAFT', craftId: 'crf_paper_crown' },
  },
  {
    id: 'act_craft_leaf_print',
    grades: [1, 2, 3],
    subject: 'craft',
    kind: 'CRAFT',
    islandId: 'crafts',
    title: 'Leaf Print',
    icon: 'leaf',
    color: palette.leaf,
    voiceIntro: "Let's paint a leaf and press it on paper to make a leaf print!",
    instruction: 'Follow the steps to make a leaf print.',
    reward: { diamonds: 6, stickerId: 'stk_leaf' },
    tags: ['craft', 'nature', 'painting'],
    data: { kind: 'CRAFT', craftId: 'crf_leaf_print' },
  },
];
