import type { ActivityDefinition } from '@/domain/activity/schema';
import { palette } from '@/theme';

/** Tracing activities: 26 uppercase letters, 10 digits, 6 shapes. */
export const tracingActivities: ActivityDefinition[] = [
  {
    id: 'act_trace_a',
    kind: 'TRACE',
    islandId: 'letters',
    title: 'Trace A',
    icon: 'apple',
    color: palette.blossom,
    voiceIntro: "Let's trace the letter A! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'letters'],
    data: {
      kind: 'TRACE',
      glyph: 'A',
      strokes: [
        {
          points: [
            { x: 0.5, y: 0.15 },
            { x: 0.18, y: 0.85 },
          ],
        },
        {
          points: [
            { x: 0.5, y: 0.15 },
            { x: 0.82, y: 0.85 },
          ],
        },
        {
          points: [
            { x: 0.27, y: 0.54 },
            { x: 0.73, y: 0.54 },
          ],
        },
      ],
      sayName: 'Big letter A.',
      sayExample: 'A is for apple!',
      examplePicture: { icon: 'apple', color: palette.leaf },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_b',
    kind: 'TRACE',
    islandId: 'letters',
    title: 'Trace B',
    icon: 'ball',
    color: palette.aqua,
    voiceIntro: "Let's trace the letter B! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'letters'],
    data: {
      kind: 'TRACE',
      glyph: 'B',
      strokes: [
        {
          points: [
            { x: 0.25, y: 0.15 },
            { x: 0.25, y: 0.85 },
          ],
        },
        {
          points: [
            { x: 0.25, y: 0.15 },
            { x: 0.5, y: 0.17 },
            { x: 0.65, y: 0.24 },
            { x: 0.7, y: 0.33 },
            { x: 0.68, y: 0.43 },
            { x: 0.55, y: 0.5 },
            { x: 0.25, y: 0.5 },
            { x: 0.62, y: 0.51 },
            { x: 0.75, y: 0.62 },
            { x: 0.75, y: 0.73 },
            { x: 0.62, y: 0.83 },
            { x: 0.25, y: 0.85 },
          ],
        },
      ],
      sayName: 'Big letter B.',
      sayExample: 'B is for ball!',
      examplePicture: { icon: 'ball', color: palette.coral },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_c',
    kind: 'TRACE',
    islandId: 'letters',
    title: 'Trace C',
    icon: 'cat',
    color: palette.sunshine,
    voiceIntro: "Let's trace the letter C! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'letters'],
    data: {
      kind: 'TRACE',
      glyph: 'C',
      strokes: [
        {
          points: [
            { x: 0.75, y: 0.24 },
            { x: 0.62, y: 0.16 },
            { x: 0.48, y: 0.15 },
            { x: 0.33, y: 0.2 },
            { x: 0.22, y: 0.31 },
            { x: 0.17, y: 0.44 },
            { x: 0.17, y: 0.56 },
            { x: 0.22, y: 0.69 },
            { x: 0.33, y: 0.8 },
            { x: 0.48, y: 0.85 },
            { x: 0.62, y: 0.84 },
            { x: 0.75, y: 0.76 },
          ],
        },
      ],
      sayName: 'Big letter C.',
      sayExample: 'C is for cat!',
      examplePicture: { icon: 'cat', color: palette.tangerine },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_d',
    kind: 'TRACE',
    islandId: 'letters',
    title: 'Trace D',
    icon: 'dog',
    color: palette.leaf,
    voiceIntro: "Let's trace the letter D! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'letters'],
    data: {
      kind: 'TRACE',
      glyph: 'D',
      strokes: [
        {
          points: [
            { x: 0.25, y: 0.15 },
            { x: 0.25, y: 0.85 },
          ],
        },
        {
          points: [
            { x: 0.25, y: 0.15 },
            { x: 0.5, y: 0.17 },
            { x: 0.68, y: 0.26 },
            { x: 0.78, y: 0.4 },
            { x: 0.8, y: 0.5 },
            { x: 0.78, y: 0.6 },
            { x: 0.68, y: 0.74 },
            { x: 0.5, y: 0.83 },
            { x: 0.25, y: 0.85 },
          ],
        },
      ],
      sayName: 'Big letter D.',
      sayExample: 'D is for dog!',
      examplePicture: { icon: 'dog', color: palette.tangerine },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_e',
    kind: 'TRACE',
    islandId: 'letters',
    title: 'Trace E',
    icon: 'ear',
    color: palette.lavender,
    voiceIntro: "Let's trace the letter E! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'letters'],
    data: {
      kind: 'TRACE',
      glyph: 'E',
      strokes: [
        {
          points: [
            { x: 0.22, y: 0.15 },
            { x: 0.22, y: 0.85 },
          ],
        },
        {
          points: [
            { x: 0.22, y: 0.15 },
            { x: 0.75, y: 0.15 },
          ],
        },
        {
          points: [
            { x: 0.22, y: 0.5 },
            { x: 0.67, y: 0.5 },
          ],
        },
        {
          points: [
            { x: 0.22, y: 0.85 },
            { x: 0.75, y: 0.85 },
          ],
        },
      ],
      sayName: 'Big letter E.',
      sayExample: 'E is for ear!',
      examplePicture: { icon: 'ear', color: palette.blossom },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_f',
    kind: 'TRACE',
    islandId: 'letters',
    title: 'Trace F',
    icon: 'fish',
    color: palette.tangerine,
    voiceIntro: "Let's trace the letter F! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'letters'],
    data: {
      kind: 'TRACE',
      glyph: 'F',
      strokes: [
        {
          points: [
            { x: 0.22, y: 0.15 },
            { x: 0.22, y: 0.85 },
          ],
        },
        {
          points: [
            { x: 0.22, y: 0.15 },
            { x: 0.75, y: 0.15 },
          ],
        },
        {
          points: [
            { x: 0.22, y: 0.5 },
            { x: 0.67, y: 0.5 },
          ],
        },
      ],
      sayName: 'Big letter F.',
      sayExample: 'F is for fish!',
      examplePicture: { icon: 'fish', color: palette.aqua },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_g',
    kind: 'TRACE',
    islandId: 'letters',
    title: 'Trace G',
    icon: 'gift',
    color: palette.blossom,
    voiceIntro: "Let's trace the letter G! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'letters'],
    data: {
      kind: 'TRACE',
      glyph: 'G',
      strokes: [
        {
          points: [
            { x: 0.75, y: 0.24 },
            { x: 0.62, y: 0.16 },
            { x: 0.48, y: 0.15 },
            { x: 0.33, y: 0.2 },
            { x: 0.22, y: 0.31 },
            { x: 0.17, y: 0.44 },
            { x: 0.17, y: 0.56 },
            { x: 0.22, y: 0.69 },
            { x: 0.33, y: 0.8 },
            { x: 0.48, y: 0.85 },
            { x: 0.62, y: 0.84 },
            { x: 0.75, y: 0.76 },
            { x: 0.75, y: 0.5 },
            { x: 0.5, y: 0.5 },
          ],
        },
      ],
      sayName: 'Big letter G.',
      sayExample: 'G is for gift!',
      examplePicture: { icon: 'gift', color: palette.blossom },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_h',
    kind: 'TRACE',
    islandId: 'letters',
    title: 'Trace H',
    icon: 'hat',
    color: palette.aqua,
    voiceIntro: "Let's trace the letter H! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'letters'],
    data: {
      kind: 'TRACE',
      glyph: 'H',
      strokes: [
        {
          points: [
            { x: 0.22, y: 0.15 },
            { x: 0.22, y: 0.85 },
          ],
        },
        {
          points: [
            { x: 0.78, y: 0.15 },
            { x: 0.78, y: 0.85 },
          ],
        },
        {
          points: [
            { x: 0.22, y: 0.5 },
            { x: 0.78, y: 0.5 },
          ],
        },
      ],
      sayName: 'Big letter H.',
      sayExample: 'H is for hat!',
      examplePicture: { icon: 'hat', color: palette.sunshine },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_i',
    kind: 'TRACE',
    islandId: 'letters',
    title: 'Trace I',
    icon: 'island',
    color: palette.sunshine,
    voiceIntro: "Let's trace the letter I! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'letters'],
    data: {
      kind: 'TRACE',
      glyph: 'I',
      strokes: [
        {
          points: [
            { x: 0.33, y: 0.15 },
            { x: 0.67, y: 0.15 },
          ],
        },
        {
          points: [
            { x: 0.5, y: 0.15 },
            { x: 0.5, y: 0.85 },
          ],
        },
        {
          points: [
            { x: 0.33, y: 0.85 },
            { x: 0.67, y: 0.85 },
          ],
        },
      ],
      sayName: 'Big letter I.',
      sayExample: 'I is for island!',
      examplePicture: { icon: 'island', color: palette.aqua },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_j',
    kind: 'TRACE',
    islandId: 'letters',
    title: 'Trace J',
    icon: 'jeepney',
    color: palette.leaf,
    voiceIntro: "Let's trace the letter J! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'letters'],
    data: {
      kind: 'TRACE',
      glyph: 'J',
      strokes: [
        {
          points: [
            { x: 0.37, y: 0.15 },
            { x: 0.73, y: 0.15 },
          ],
        },
        {
          points: [
            { x: 0.62, y: 0.15 },
            { x: 0.62, y: 0.7 },
            { x: 0.56, y: 0.81 },
            { x: 0.44, y: 0.86 },
            { x: 0.32, y: 0.81 },
            { x: 0.27, y: 0.7 },
          ],
        },
      ],
      sayName: 'Big letter J.',
      sayExample: 'J is for jeepney!',
      examplePicture: { icon: 'jeepney', color: palette.sunshine },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_k',
    kind: 'TRACE',
    islandId: 'letters',
    title: 'Trace K',
    icon: 'crown',
    color: palette.lavender,
    voiceIntro: "Let's trace the letter K! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'letters'],
    data: {
      kind: 'TRACE',
      glyph: 'K',
      strokes: [
        {
          points: [
            { x: 0.22, y: 0.15 },
            { x: 0.22, y: 0.85 },
          ],
        },
        {
          points: [
            { x: 0.72, y: 0.15 },
            { x: 0.22, y: 0.5 },
          ],
        },
        {
          points: [
            { x: 0.22, y: 0.5 },
            { x: 0.72, y: 0.85 },
          ],
        },
      ],
      sayName: 'Big letter K.',
      sayExample: 'K is for king!',
      examplePicture: { icon: 'crown', color: palette.sunshine },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_l',
    kind: 'TRACE',
    islandId: 'letters',
    title: 'Trace L',
    icon: 'leaf',
    color: palette.tangerine,
    voiceIntro: "Let's trace the letter L! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'letters'],
    data: {
      kind: 'TRACE',
      glyph: 'L',
      strokes: [
        {
          points: [
            { x: 0.25, y: 0.15 },
            { x: 0.25, y: 0.85 },
          ],
        },
        {
          points: [
            { x: 0.25, y: 0.85 },
            { x: 0.72, y: 0.85 },
          ],
        },
      ],
      sayName: 'Big letter L.',
      sayExample: 'L is for leaf!',
      examplePicture: { icon: 'leaf', color: palette.leaf },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_m',
    kind: 'TRACE',
    islandId: 'letters',
    title: 'Trace M',
    icon: 'mango',
    color: palette.blossom,
    voiceIntro: "Let's trace the letter M! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'letters'],
    data: {
      kind: 'TRACE',
      glyph: 'M',
      strokes: [
        {
          points: [
            { x: 0.18, y: 0.15 },
            { x: 0.18, y: 0.85 },
          ],
        },
        {
          points: [
            { x: 0.18, y: 0.15 },
            { x: 0.5, y: 0.58 },
            { x: 0.82, y: 0.15 },
          ],
        },
        {
          points: [
            { x: 0.82, y: 0.15 },
            { x: 0.82, y: 0.85 },
          ],
        },
      ],
      sayName: 'Big letter M.',
      sayExample: 'M is for mango!',
      examplePicture: { icon: 'mango', color: palette.sunshine },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_n',
    kind: 'TRACE',
    islandId: 'letters',
    title: 'Trace N',
    icon: 'nose',
    color: palette.aqua,
    voiceIntro: "Let's trace the letter N! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'letters'],
    data: {
      kind: 'TRACE',
      glyph: 'N',
      strokes: [
        {
          points: [
            { x: 0.22, y: 0.15 },
            { x: 0.22, y: 0.85 },
          ],
        },
        {
          points: [
            { x: 0.22, y: 0.15 },
            { x: 0.78, y: 0.85 },
          ],
        },
        {
          points: [
            { x: 0.78, y: 0.15 },
            { x: 0.78, y: 0.85 },
          ],
        },
      ],
      sayName: 'Big letter N.',
      sayExample: 'N is for nose!',
      examplePicture: { icon: 'nose', color: palette.blossom },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_o',
    kind: 'TRACE',
    islandId: 'letters',
    title: 'Trace O',
    icon: 'octopus',
    color: palette.sunshine,
    voiceIntro: "Let's trace the letter O! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'letters'],
    data: {
      kind: 'TRACE',
      glyph: 'O',
      strokes: [
        {
          points: [
            { x: 0.5, y: 0.15 },
            { x: 0.65, y: 0.18 },
            { x: 0.77, y: 0.28 },
            { x: 0.83, y: 0.42 },
            { x: 0.83, y: 0.58 },
            { x: 0.77, y: 0.72 },
            { x: 0.65, y: 0.82 },
            { x: 0.5, y: 0.85 },
            { x: 0.35, y: 0.82 },
            { x: 0.23, y: 0.72 },
            { x: 0.17, y: 0.58 },
            { x: 0.17, y: 0.42 },
            { x: 0.23, y: 0.28 },
            { x: 0.35, y: 0.18 },
            { x: 0.5, y: 0.15 },
          ],
        },
      ],
      sayName: 'Big letter O.',
      sayExample: 'O is for octopus!',
      examplePicture: { icon: 'octopus', color: palette.lavender },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_p',
    kind: 'TRACE',
    islandId: 'letters',
    title: 'Trace P',
    icon: 'pig',
    color: palette.leaf,
    voiceIntro: "Let's trace the letter P! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'letters'],
    data: {
      kind: 'TRACE',
      glyph: 'P',
      strokes: [
        {
          points: [
            { x: 0.25, y: 0.15 },
            { x: 0.25, y: 0.85 },
          ],
        },
        {
          points: [
            { x: 0.25, y: 0.15 },
            { x: 0.52, y: 0.17 },
            { x: 0.68, y: 0.26 },
            { x: 0.72, y: 0.36 },
            { x: 0.72, y: 0.44 },
            { x: 0.65, y: 0.52 },
            { x: 0.25, y: 0.5 },
          ],
        },
      ],
      sayName: 'Big letter P.',
      sayExample: 'P is for pig!',
      examplePicture: { icon: 'pig', color: palette.blossom },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_q',
    kind: 'TRACE',
    islandId: 'letters',
    title: 'Trace Q',
    icon: 'crown',
    color: palette.lavender,
    voiceIntro: "Let's trace the letter Q! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'letters'],
    data: {
      kind: 'TRACE',
      glyph: 'Q',
      strokes: [
        {
          points: [
            { x: 0.5, y: 0.15 },
            { x: 0.65, y: 0.18 },
            { x: 0.77, y: 0.28 },
            { x: 0.83, y: 0.42 },
            { x: 0.83, y: 0.58 },
            { x: 0.77, y: 0.72 },
            { x: 0.65, y: 0.82 },
            { x: 0.5, y: 0.85 },
            { x: 0.35, y: 0.82 },
            { x: 0.23, y: 0.72 },
            { x: 0.17, y: 0.58 },
            { x: 0.17, y: 0.42 },
            { x: 0.23, y: 0.28 },
            { x: 0.35, y: 0.18 },
            { x: 0.5, y: 0.15 },
          ],
        },
        {
          points: [
            { x: 0.6, y: 0.7 },
            { x: 0.8, y: 0.85 },
          ],
        },
      ],
      sayName: 'Big letter Q.',
      sayExample: 'Q is for queen!',
      examplePicture: { icon: 'crown', color: palette.lavender },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_r',
    kind: 'TRACE',
    islandId: 'letters',
    title: 'Trace R',
    icon: 'rainbow',
    color: palette.tangerine,
    voiceIntro: "Let's trace the letter R! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'letters'],
    data: {
      kind: 'TRACE',
      glyph: 'R',
      strokes: [
        {
          points: [
            { x: 0.25, y: 0.15 },
            { x: 0.25, y: 0.85 },
          ],
        },
        {
          points: [
            { x: 0.25, y: 0.15 },
            { x: 0.52, y: 0.17 },
            { x: 0.68, y: 0.26 },
            { x: 0.72, y: 0.36 },
            { x: 0.72, y: 0.44 },
            { x: 0.65, y: 0.52 },
            { x: 0.25, y: 0.5 },
          ],
        },
        {
          points: [
            { x: 0.45, y: 0.5 },
            { x: 0.73, y: 0.85 },
          ],
        },
      ],
      sayName: 'Big letter R.',
      sayExample: 'R is for rainbow!',
      examplePicture: { icon: 'rainbow', color: palette.blossom },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_s',
    kind: 'TRACE',
    islandId: 'letters',
    title: 'Trace S',
    icon: 'sun',
    color: palette.blossom,
    voiceIntro: "Let's trace the letter S! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'letters'],
    data: {
      kind: 'TRACE',
      glyph: 'S',
      strokes: [
        {
          points: [
            { x: 0.72, y: 0.22 },
            { x: 0.63, y: 0.16 },
            { x: 0.5, y: 0.15 },
            { x: 0.36, y: 0.17 },
            { x: 0.27, y: 0.25 },
            { x: 0.26, y: 0.35 },
            { x: 0.33, y: 0.44 },
            { x: 0.47, y: 0.5 },
            { x: 0.63, y: 0.56 },
            { x: 0.73, y: 0.65 },
            { x: 0.72, y: 0.75 },
            { x: 0.62, y: 0.84 },
            { x: 0.48, y: 0.85 },
            { x: 0.35, y: 0.83 },
            { x: 0.27, y: 0.76 },
          ],
        },
      ],
      sayName: 'Big letter S.',
      sayExample: 'S is for sun!',
      examplePicture: { icon: 'sun', color: palette.sunshine },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_t',
    kind: 'TRACE',
    islandId: 'letters',
    title: 'Trace T',
    icon: 'turtle',
    color: palette.aqua,
    voiceIntro: "Let's trace the letter T! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'letters'],
    data: {
      kind: 'TRACE',
      glyph: 'T',
      strokes: [
        {
          points: [
            { x: 0.18, y: 0.15 },
            { x: 0.82, y: 0.15 },
          ],
        },
        {
          points: [
            { x: 0.5, y: 0.15 },
            { x: 0.5, y: 0.85 },
          ],
        },
      ],
      sayName: 'Big letter T.',
      sayExample: 'T is for turtle!',
      examplePicture: { icon: 'turtle', color: palette.leaf },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_u',
    kind: 'TRACE',
    islandId: 'letters',
    title: 'Trace U',
    icon: 'rain',
    color: palette.sunshine,
    voiceIntro: "Let's trace the letter U! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'letters'],
    data: {
      kind: 'TRACE',
      glyph: 'U',
      strokes: [
        {
          points: [
            { x: 0.22, y: 0.15 },
            { x: 0.22, y: 0.65 },
            { x: 0.25, y: 0.75 },
            { x: 0.33, y: 0.83 },
            { x: 0.45, y: 0.87 },
            { x: 0.55, y: 0.87 },
            { x: 0.67, y: 0.83 },
            { x: 0.75, y: 0.75 },
            { x: 0.78, y: 0.65 },
            { x: 0.78, y: 0.15 },
          ],
        },
      ],
      sayName: 'Big letter U.',
      sayExample: 'U is for umbrella! It keeps you dry!',
      examplePicture: { icon: 'rain', color: palette.aqua },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_v',
    kind: 'TRACE',
    islandId: 'letters',
    title: 'Trace V',
    icon: 'jeepney',
    color: palette.leaf,
    voiceIntro: "Let's trace the letter V! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'letters'],
    data: {
      kind: 'TRACE',
      glyph: 'V',
      strokes: [
        {
          points: [
            { x: 0.2, y: 0.15 },
            { x: 0.5, y: 0.85 },
          ],
        },
        {
          points: [
            { x: 0.5, y: 0.85 },
            { x: 0.8, y: 0.15 },
          ],
        },
      ],
      sayName: 'Big letter V.',
      sayExample: 'V is for van!',
      examplePicture: { icon: 'jeepney', color: palette.tangerine },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_w',
    kind: 'TRACE',
    islandId: 'letters',
    title: 'Trace W',
    icon: 'whale',
    color: palette.lavender,
    voiceIntro: "Let's trace the letter W! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'letters'],
    data: {
      kind: 'TRACE',
      glyph: 'W',
      strokes: [
        {
          points: [
            { x: 0.15, y: 0.15 },
            { x: 0.3, y: 0.85 },
          ],
        },
        {
          points: [
            { x: 0.3, y: 0.85 },
            { x: 0.5, y: 0.42 },
            { x: 0.7, y: 0.85 },
          ],
        },
        {
          points: [
            { x: 0.7, y: 0.85 },
            { x: 0.85, y: 0.15 },
          ],
        },
      ],
      sayName: 'Big letter W.',
      sayExample: 'W is for whale!',
      examplePicture: { icon: 'whale', color: palette.sea },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_x',
    kind: 'TRACE',
    islandId: 'letters',
    title: 'Trace X',
    icon: 'music',
    color: palette.tangerine,
    voiceIntro: "Let's trace the letter X! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'letters'],
    data: {
      kind: 'TRACE',
      glyph: 'X',
      strokes: [
        {
          points: [
            { x: 0.2, y: 0.15 },
            { x: 0.8, y: 0.85 },
          ],
        },
        {
          points: [
            { x: 0.8, y: 0.15 },
            { x: 0.2, y: 0.85 },
          ],
        },
      ],
      sayName: 'Big letter X.',
      sayExample: 'X is for xylophone!',
      examplePicture: { icon: 'music', color: palette.lavender },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_y',
    kind: 'TRACE',
    islandId: 'letters',
    title: 'Trace Y',
    icon: 'sun',
    color: palette.blossom,
    voiceIntro: "Let's trace the letter Y! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'letters'],
    data: {
      kind: 'TRACE',
      glyph: 'Y',
      strokes: [
        {
          points: [
            { x: 0.2, y: 0.15 },
            { x: 0.5, y: 0.5 },
          ],
        },
        {
          points: [
            { x: 0.8, y: 0.15 },
            { x: 0.5, y: 0.5 },
          ],
        },
        {
          points: [
            { x: 0.5, y: 0.5 },
            { x: 0.5, y: 0.85 },
          ],
        },
      ],
      sayName: 'Big letter Y.',
      sayExample: 'Y is for yellow!',
      examplePicture: { icon: 'sun', color: palette.sunshine },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_z',
    kind: 'TRACE',
    islandId: 'letters',
    title: 'Trace Z',
    icon: 'star',
    color: palette.aqua,
    voiceIntro: "Let's trace the letter Z! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'letters'],
    data: {
      kind: 'TRACE',
      glyph: 'Z',
      strokes: [
        {
          points: [
            { x: 0.2, y: 0.15 },
            { x: 0.8, y: 0.15 },
          ],
        },
        {
          points: [
            { x: 0.8, y: 0.15 },
            { x: 0.2, y: 0.85 },
          ],
        },
        {
          points: [
            { x: 0.2, y: 0.85 },
            { x: 0.8, y: 0.85 },
          ],
        },
      ],
      sayName: 'Big letter Z.',
      sayExample: 'Z is for zigzag!',
      examplePicture: { icon: 'star', color: palette.sunshine },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_0',
    kind: 'TRACE',
    islandId: 'numbers',
    title: 'Trace 0',
    icon: 'coconut',
    color: palette.sunshine,
    voiceIntro: "Let's trace the number 0! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'numbers'],
    data: {
      kind: 'TRACE',
      glyph: '0',
      strokes: [
        {
          points: [
            { x: 0.5, y: 0.15 },
            { x: 0.65, y: 0.18 },
            { x: 0.77, y: 0.27 },
            { x: 0.82, y: 0.42 },
            { x: 0.82, y: 0.58 },
            { x: 0.77, y: 0.73 },
            { x: 0.65, y: 0.83 },
            { x: 0.5, y: 0.85 },
            { x: 0.35, y: 0.83 },
            { x: 0.23, y: 0.73 },
            { x: 0.18, y: 0.58 },
            { x: 0.18, y: 0.42 },
            { x: 0.23, y: 0.27 },
            { x: 0.35, y: 0.18 },
            { x: 0.5, y: 0.15 },
          ],
        },
      ],
      sayName: 'Number zero.',
      sayExample: 'Zero! Nothing at all.',
      examplePicture: { icon: 'coconut', color: palette.leaf },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_1',
    kind: 'TRACE',
    islandId: 'numbers',
    title: 'Trace 1',
    icon: 'fish',
    color: palette.leaf,
    voiceIntro: "Let's trace the number 1! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'numbers'],
    data: {
      kind: 'TRACE',
      glyph: '1',
      strokes: [
        {
          points: [
            { x: 0.37, y: 0.28 },
            { x: 0.52, y: 0.15 },
          ],
        },
        {
          points: [
            { x: 0.52, y: 0.15 },
            { x: 0.52, y: 0.85 },
          ],
        },
      ],
      sayName: 'Number one.',
      sayExample: 'One fish!',
      examplePicture: { icon: 'fish', color: palette.aqua },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_2',
    kind: 'TRACE',
    islandId: 'numbers',
    title: 'Trace 2',
    icon: 'crab',
    color: palette.lavender,
    voiceIntro: "Let's trace the number 2! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'numbers'],
    data: {
      kind: 'TRACE',
      glyph: '2',
      strokes: [
        {
          points: [
            { x: 0.27, y: 0.3 },
            { x: 0.32, y: 0.2 },
            { x: 0.42, y: 0.15 },
            { x: 0.55, y: 0.15 },
            { x: 0.68, y: 0.2 },
            { x: 0.75, y: 0.3 },
            { x: 0.72, y: 0.42 },
            { x: 0.6, y: 0.54 },
            { x: 0.45, y: 0.65 },
            { x: 0.3, y: 0.76 },
            { x: 0.22, y: 0.85 },
            { x: 0.78, y: 0.85 },
          ],
        },
      ],
      sayName: 'Number two.',
      sayExample: 'Two crabs!',
      examplePicture: { icon: 'crab', color: palette.coral },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_3',
    kind: 'TRACE',
    islandId: 'numbers',
    title: 'Trace 3',
    icon: 'bird',
    color: palette.tangerine,
    voiceIntro: "Let's trace the number 3! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'numbers'],
    data: {
      kind: 'TRACE',
      glyph: '3',
      strokes: [
        {
          points: [
            { x: 0.28, y: 0.22 },
            { x: 0.38, y: 0.15 },
            { x: 0.55, y: 0.15 },
            { x: 0.68, y: 0.22 },
            { x: 0.73, y: 0.33 },
            { x: 0.7, y: 0.45 },
            { x: 0.57, y: 0.5 },
            { x: 0.48, y: 0.5 },
            { x: 0.62, y: 0.52 },
            { x: 0.73, y: 0.6 },
            { x: 0.75, y: 0.73 },
            { x: 0.68, y: 0.83 },
            { x: 0.52, y: 0.87 },
            { x: 0.36, y: 0.85 },
            { x: 0.27, y: 0.77 },
          ],
        },
      ],
      sayName: 'Number three.',
      sayExample: 'Three birds!',
      examplePicture: { icon: 'bird', color: palette.aqua },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_4',
    kind: 'TRACE',
    islandId: 'numbers',
    title: 'Trace 4',
    icon: 'butterfly',
    color: palette.blossom,
    voiceIntro: "Let's trace the number 4! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'numbers'],
    data: {
      kind: 'TRACE',
      glyph: '4',
      strokes: [
        {
          points: [
            { x: 0.65, y: 0.15 },
            { x: 0.22, y: 0.63 },
            { x: 0.78, y: 0.63 },
          ],
        },
        {
          points: [
            { x: 0.65, y: 0.15 },
            { x: 0.65, y: 0.85 },
          ],
        },
      ],
      sayName: 'Number four.',
      sayExample: 'Four butterflies!',
      examplePicture: { icon: 'butterfly', color: palette.blossom },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_5',
    kind: 'TRACE',
    islandId: 'numbers',
    title: 'Trace 5',
    icon: 'frog',
    color: palette.aqua,
    voiceIntro: "Let's trace the number 5! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'numbers'],
    data: {
      kind: 'TRACE',
      glyph: '5',
      strokes: [
        {
          points: [
            { x: 0.72, y: 0.15 },
            { x: 0.27, y: 0.15 },
            { x: 0.27, y: 0.5 },
          ],
        },
        {
          points: [
            { x: 0.27, y: 0.5 },
            { x: 0.42, y: 0.47 },
            { x: 0.58, y: 0.48 },
            { x: 0.7, y: 0.57 },
            { x: 0.73, y: 0.68 },
            { x: 0.68, y: 0.8 },
            { x: 0.55, y: 0.87 },
            { x: 0.4, y: 0.87 },
            { x: 0.27, y: 0.82 },
          ],
        },
      ],
      sayName: 'Number five.',
      sayExample: 'Five frogs!',
      examplePicture: { icon: 'frog', color: palette.leaf },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_6',
    kind: 'TRACE',
    islandId: 'numbers',
    title: 'Trace 6',
    icon: 'shell',
    color: palette.sunshine,
    voiceIntro: "Let's trace the number 6! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'numbers'],
    data: {
      kind: 'TRACE',
      glyph: '6',
      strokes: [
        {
          points: [
            { x: 0.65, y: 0.15 },
            { x: 0.5, y: 0.15 },
            { x: 0.35, y: 0.2 },
            { x: 0.22, y: 0.33 },
            { x: 0.18, y: 0.48 },
            { x: 0.2, y: 0.63 },
            { x: 0.3, y: 0.77 },
            { x: 0.45, y: 0.85 },
            { x: 0.58, y: 0.85 },
            { x: 0.7, y: 0.78 },
            { x: 0.78, y: 0.67 },
            { x: 0.78, y: 0.55 },
            { x: 0.7, y: 0.45 },
            { x: 0.57, y: 0.4 },
            { x: 0.43, y: 0.4 },
            { x: 0.3, y: 0.45 },
            { x: 0.22, y: 0.55 },
          ],
        },
      ],
      sayName: 'Number six.',
      sayExample: 'Six shells!',
      examplePicture: { icon: 'shell', color: palette.blossom },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_7',
    kind: 'TRACE',
    islandId: 'numbers',
    title: 'Trace 7',
    icon: 'starfish',
    color: palette.leaf,
    voiceIntro: "Let's trace the number 7! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'numbers'],
    data: {
      kind: 'TRACE',
      glyph: '7',
      strokes: [
        {
          points: [
            { x: 0.2, y: 0.15 },
            { x: 0.8, y: 0.15 },
          ],
        },
        {
          points: [
            { x: 0.8, y: 0.15 },
            { x: 0.4, y: 0.85 },
          ],
        },
      ],
      sayName: 'Number seven.',
      sayExample: 'Seven starfish!',
      examplePicture: { icon: 'starfish', color: palette.coral },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_8',
    kind: 'TRACE',
    islandId: 'numbers',
    title: 'Trace 8',
    icon: 'bee',
    color: palette.lavender,
    voiceIntro: "Let's trace the number 8! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'numbers'],
    data: {
      kind: 'TRACE',
      glyph: '8',
      strokes: [
        {
          points: [
            { x: 0.5, y: 0.5 },
            { x: 0.64, y: 0.48 },
            { x: 0.75, y: 0.4 },
            { x: 0.77, y: 0.3 },
            { x: 0.72, y: 0.2 },
            { x: 0.6, y: 0.15 },
            { x: 0.48, y: 0.15 },
            { x: 0.35, y: 0.18 },
            { x: 0.25, y: 0.27 },
            { x: 0.24, y: 0.38 },
            { x: 0.3, y: 0.47 },
            { x: 0.42, y: 0.5 },
            { x: 0.5, y: 0.5 },
          ],
        },
        {
          points: [
            { x: 0.5, y: 0.5 },
            { x: 0.62, y: 0.52 },
            { x: 0.75, y: 0.6 },
            { x: 0.77, y: 0.7 },
            { x: 0.72, y: 0.8 },
            { x: 0.6, y: 0.85 },
            { x: 0.48, y: 0.86 },
            { x: 0.35, y: 0.83 },
            { x: 0.25, y: 0.75 },
            { x: 0.23, y: 0.63 },
            { x: 0.3, y: 0.53 },
            { x: 0.42, y: 0.5 },
            { x: 0.5, y: 0.5 },
          ],
        },
      ],
      sayName: 'Number eight.',
      sayExample: 'Eight bees!',
      examplePicture: { icon: 'bee', color: palette.sunshine },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_9',
    kind: 'TRACE',
    islandId: 'numbers',
    title: 'Trace 9',
    icon: 'flower',
    color: palette.tangerine,
    voiceIntro: "Let's trace the number 9! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 2 },
    tags: ['tracing', 'numbers'],
    data: {
      kind: 'TRACE',
      glyph: '9',
      strokes: [
        {
          points: [
            { x: 0.78, y: 0.3 },
            { x: 0.7, y: 0.18 },
            { x: 0.57, y: 0.14 },
            { x: 0.43, y: 0.15 },
            { x: 0.3, y: 0.22 },
            { x: 0.22, y: 0.34 },
            { x: 0.22, y: 0.47 },
            { x: 0.28, y: 0.58 },
            { x: 0.4, y: 0.64 },
            { x: 0.54, y: 0.64 },
            { x: 0.66, y: 0.58 },
            { x: 0.75, y: 0.47 },
            { x: 0.78, y: 0.34 },
            { x: 0.78, y: 0.7 },
            { x: 0.72, y: 0.82 },
            { x: 0.6, y: 0.87 },
          ],
        },
      ],
      sayName: 'Number nine.',
      sayExample: 'Nine flowers!',
      examplePicture: { icon: 'flower', color: palette.blossom },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_shape_circle',
    kind: 'TRACE',
    islandId: 'numbers',
    title: 'Trace a Circle',
    icon: 'sun',
    color: palette.blossom,
    voiceIntro: "Let's trace a circle! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 3, stickerId: 'stk_star' },
    tags: ['tracing', 'shapes'],
    data: {
      kind: 'TRACE',
      glyph: 'circle',
      strokes: [
        {
          points: [
            { x: 0.5, y: 0.15 },
            { x: 0.6339, y: 0.1766 },
            { x: 0.7475, y: 0.2525 },
            { x: 0.8234, y: 0.3661 },
            { x: 0.85, y: 0.5 },
            { x: 0.8234, y: 0.6339 },
            { x: 0.7475, y: 0.7475 },
            { x: 0.6339, y: 0.8234 },
            { x: 0.5, y: 0.85 },
            { x: 0.3661, y: 0.8234 },
            { x: 0.2525, y: 0.7475 },
            { x: 0.1766, y: 0.6339 },
            { x: 0.15, y: 0.5 },
            { x: 0.1766, y: 0.3661 },
            { x: 0.2525, y: 0.2525 },
            { x: 0.3661, y: 0.1766 },
            { x: 0.5, y: 0.15 },
          ],
        },
      ],
      sayName: 'A circle.',
      sayExample: 'A circle is round like the sun!',
      examplePicture: { icon: 'sun', color: palette.sunshine },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_shape_square',
    kind: 'TRACE',
    islandId: 'numbers',
    title: 'Trace a Square',
    icon: 'gift',
    color: palette.aqua,
    voiceIntro: "Let's trace a square! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 3, stickerId: 'stk_star' },
    tags: ['tracing', 'shapes'],
    data: {
      kind: 'TRACE',
      glyph: 'square',
      strokes: [
        {
          points: [
            { x: 0.15, y: 0.15 },
            { x: 0.85, y: 0.15 },
            { x: 0.85, y: 0.85 },
            { x: 0.15, y: 0.85 },
            { x: 0.15, y: 0.15 },
          ],
        },
      ],
      sayName: 'A square.',
      sayExample: 'A square has four equal sides!',
      examplePicture: { icon: 'gift', color: palette.blossom },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_shape_triangle',
    kind: 'TRACE',
    islandId: 'numbers',
    title: 'Trace a Triangle',
    icon: 'boat',
    color: palette.sunshine,
    voiceIntro: "Let's trace a triangle! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 3, stickerId: 'stk_star' },
    tags: ['tracing', 'shapes'],
    data: {
      kind: 'TRACE',
      glyph: 'triangle',
      strokes: [
        {
          points: [
            { x: 0.5, y: 0.13 },
            { x: 0.85, y: 0.85 },
            { x: 0.15, y: 0.85 },
            { x: 0.5, y: 0.13 },
          ],
        },
      ],
      sayName: 'A triangle.',
      sayExample: 'A triangle has three corners!',
      examplePicture: { icon: 'boat', color: palette.aqua },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_shape_star',
    kind: 'TRACE',
    islandId: 'numbers',
    title: 'Trace a Star',
    icon: 'starfish',
    color: palette.leaf,
    voiceIntro: "Let's trace a star! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 3, stickerId: 'stk_star' },
    tags: ['tracing', 'shapes'],
    data: {
      kind: 'TRACE',
      glyph: 'star',
      strokes: [
        {
          points: [
            { x: 0.5, y: 0.13 },
            { x: 0.5882, y: 0.3786 },
            { x: 0.8519, y: 0.3857 },
            { x: 0.6427, y: 0.5464 },
            { x: 0.7175, y: 0.7993 },
            { x: 0.5, y: 0.65 },
            { x: 0.2825, y: 0.7993 },
            { x: 0.3573, y: 0.5464 },
            { x: 0.1481, y: 0.3857 },
            { x: 0.4118, y: 0.3786 },
            { x: 0.5, y: 0.13 },
          ],
        },
      ],
      sayName: 'A star.',
      sayExample: 'A star has five points, like a starfish!',
      examplePicture: { icon: 'starfish', color: palette.coral },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_shape_heart',
    kind: 'TRACE',
    islandId: 'numbers',
    title: 'Trace a Heart',
    icon: 'flower',
    color: palette.lavender,
    voiceIntro: "Let's trace a heart! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 3, stickerId: 'stk_star' },
    tags: ['tracing', 'shapes'],
    data: {
      kind: 'TRACE',
      glyph: 'heart',
      strokes: [
        {
          points: [
            { x: 0.5, y: 0.3 },
            { x: 0.59, y: 0.21 },
            { x: 0.7, y: 0.18 },
            { x: 0.8, y: 0.22 },
            { x: 0.86, y: 0.33 },
            { x: 0.85, y: 0.45 },
            { x: 0.77, y: 0.57 },
            { x: 0.64, y: 0.67 },
            { x: 0.5, y: 0.8 },
            { x: 0.36, y: 0.67 },
            { x: 0.23, y: 0.57 },
            { x: 0.15, y: 0.45 },
            { x: 0.14, y: 0.33 },
            { x: 0.2, y: 0.22 },
            { x: 0.3, y: 0.18 },
            { x: 0.41, y: 0.21 },
            { x: 0.5, y: 0.3 },
          ],
        },
      ],
      sayName: 'A heart.',
      sayExample: 'A heart means love!',
      examplePicture: { icon: 'flower', color: palette.blossom },
      tolerance: 0.09,
    },
  },
  {
    id: 'act_trace_shape_diamond',
    kind: 'TRACE',
    islandId: 'numbers',
    title: 'Trace a Diamond',
    icon: 'diamond',
    color: palette.tangerine,
    voiceIntro: "Let's trace a diamond! Start at the dot.",
    instruction: 'Follow the dotted line.',
    reward: { diamonds: 3, stickerId: 'stk_star' },
    tags: ['tracing', 'shapes'],
    data: {
      kind: 'TRACE',
      glyph: 'diamond',
      strokes: [
        {
          points: [
            { x: 0.5, y: 0.12 },
            { x: 0.85, y: 0.5 },
            { x: 0.5, y: 0.88 },
            { x: 0.15, y: 0.5 },
            { x: 0.5, y: 0.12 },
          ],
        },
      ],
      sayName: 'A diamond.',
      sayExample: 'A diamond sparkles and shines!',
      examplePicture: { icon: 'diamond', color: palette.tangerine },
      tolerance: 0.09,
    },
  },
];
