/** Adult-facing copy for Parent Mode. Plain, honest, no marketing. */
export const parentStrings = {
  gate: {
    title: 'Grown-ups only',
    holdHint: 'Press and hold the lock to continue.',
    hold: 'Hold to open',
    question: (a: number, b: number) => `What is ${a} + ${b}?`,
    pinTitle: 'Enter your parent PIN',
    wrong: 'Not quite — try again.',
    backToIsland: 'Back to Diamond Island',
  },
  home: {
    title: 'Parent Mode',
    intro: 'Everything here is for grown-ups. Nothing on this side is visible to your child.',
    settings: 'Settings',
    settingsHint: 'Music, sounds, voice, motion, PIN, nickname',
    creations: 'Creations',
    creationsHint: 'Rename, export or delete',
    learning: 'Learning',
    learningHint: 'Grade level, progress, content updates',
    privacy: 'Privacy & storage',
    privacyHint: 'What is stored and where',
    exit: 'Exit Parent Mode',
  },
  learning: {
    title: 'Learning',
    hint: 'Grade level, progress and what the app is teaching',
    grade: 'Grade level',
    gradeHint: 'Philippines K-12 Grades 1–6. Islands show activities for this grade.',
    autoAdvance: 'Move up a grade automatically',
    autoAdvanceHint:
      'When most of a grade’s core activities are done well (80%+), the next grade unlocks. It never moves down.',
    report: 'Progress report',
    mastery: (done: number, total: number) => `${done} of ${total} core activities mastered`,
    diamonds: (n: number) => `${n} diamonds earned`,
    activitiesDone: (n: number) => `${n} activities completed`,
    subjects: 'By subject',
    noData: 'No activities completed yet.',
    content: 'Content updates',
    contentHint:
      'New activities are downloaded from the app’s own website when online. Nothing else is fetched; nothing is sent.',
    lastUpdate: (when: string) => `Last check: ${when}`,
    never: 'never',
    checkNow: 'Check for new activities',
    upToDate: 'Up to date.',
    updated: (n: number) => `${n} activities added or updated.`,
    offline: 'Could not reach the website. Try again later.',
  },
  settings: {
    title: 'Settings',
    audio: 'Audio',
    music: 'Music',
    soundEffects: 'Sound effects',
    voice: 'Voice guidance',
    motion: 'Motion',
    reducedMotion: 'Reduce animations',
    reducedMotionHint: 'Off follows the device setting.',
    profile: 'Child profile',
    nickname: 'Nickname',
    nicknameHint: 'A nickname only. Never a full name.',
    pin: 'Parent PIN',
    pinHint: 'Optional 4 digits. Replaces the arithmetic question at the gate.',
    setPin: 'Set PIN',
    clearPin: 'Remove PIN',
    pinSaved: 'PIN saved.',
    pinInvalid: 'Enter exactly 4 digits.',
    intro: 'Intro',
    replayIntro: 'Show the intro again next time',
    cloud: 'Cloud backup',
    cloudOff: 'Off. Creations stay on this device only.',
    cloudOn: 'On. Backups run only while a parent is signed in.',
    cloudUnavailable: 'Cloud backup is not configured in this build.',
    cloudSync: 'Back up creations to the cloud',
  },
  creations: {
    title: 'Creations',
    empty: 'No creations yet.',
    rename: 'Rename',
    export: 'Export',
    delete: 'Delete',
    confirmDelete: 'Delete this creation? This cannot be undone.',
    confirmDeleteAll: 'Delete ALL creations and garden progress? This cannot be undone.',
    deleteAll: 'Delete everything',
    exportUnavailable: 'This creation uses a built-in picture and has no file to export.',
    save: 'Save',
    cancel: 'Cancel',
  },
  privacy: {
    title: 'Privacy & storage',
    storage: (mb: string, count: number) =>
      `${count} creation${count === 1 ? '' : 's'} · ${mb} MB on this device`,
    bullets: [
      'Everything your child makes is stored only on this device.',
      'Photos are never analysed, never uploaded, and never used to train anything.',
      'The app collects no name, address, school, contacts, location or email.',
      'There are no ads, no tracking, no social features and no chat.',
      'Voice prompts use the device’s own speech engine — nothing leaves the device.',
      'Music and voice are placeholders in this build and will be replaced by original recordings.',
    ],
    logs: 'Technical log (for troubleshooting)',
  },
} as const;
