/** Central route table. Screens navigate through these, never through string literals. */
export const routes = {
  intro: '/',
  home: '/home',
  create: '/create',
  draw: '/create/draw',
  craft: (craftId: string) => `/create/craft/${craftId}` as const,
  island: (islandId: string) => `/island/${islandId}` as const,
  play: (activityId: string) => `/play/${activityId}` as const,
  quest: '/quest',
  stickers: '/stickers',
  garden: '/garden',
  music: '/music',
  book: '/book',
  creation: (creationId: string) => `/book/${creationId}` as const,
  parentGate: '/parent',
  parentHome: '/parent/home',
  parentSettings: '/parent/settings',
  parentLearning: '/parent/learning',
  parentCreations: '/parent/creations',
  parentPrivacy: '/parent/privacy',
} as const;
