import type { CraftTemplate } from '@/domain/craft/schema';

/** Leaf Print — paint a real leaf and press it onto paper. Nature meets art. */
export const leafPrint: CraftTemplate = {
  id: 'crf_leaf_print',
  title: 'Leaf Print',
  noun: 'leaf print',
  description: 'Paint the back of a leaf and press it on paper to print its shape and veins.',
  icon: 'leaf',
  illustration: 'craft.leafPrint.7',
  difficulty: 'EASY',
  estimatedMinutes: 10,
  materials: ['a big leaf from the garden', 'paints', 'a paintbrush', 'white paper'],
  tags: ['nature', 'painting', 'science', 'printing'],
  reward: { creativityPoints: 5, gardenItemId: 'tree' },
  completionAction: 'SAVE_PHOTO',
  steps: [
    {
      id: 'leaf',
      order: 0,
      kind: 'INSTRUCTION',
      instruction: 'Find a big leaf.',
      illustration: 'craft.leafPrint.1',
      audioPrompt: "Let's make a leaf print! Find a big leaf and get your paints ready.",
      animation: 'bounce',
    },
    {
      id: 'paint',
      order: 1,
      kind: 'INSTRUCTION',
      instruction: 'Paint the back of the leaf.',
      illustration: 'craft.leafPrint.2',
      audioPrompt: 'Paint the bumpy back of the leaf. That side has the lines!',
      animation: 'wiggle',
    },
    {
      id: 'press',
      order: 2,
      kind: 'INSTRUCTION',
      instruction: 'Press it onto the paper.',
      illustration: 'craft.leafPrint.3',
      audioPrompt: 'Turn the leaf over and press it gently onto the paper.',
      animation: 'grow',
    },
    {
      id: 'lift',
      order: 3,
      kind: 'INSTRUCTION',
      instruction: 'Lift the leaf. Look!',
      illustration: 'craft.leafPrint.4',
      audioPrompt: 'Lift the leaf slowly. Look at the lines! Those are the leaf veins.',
      animation: 'sparkle',
    },
    {
      id: 'more',
      order: 4,
      kind: 'INSTRUCTION',
      instruction: 'Make more prints in other colors.',
      illustration: 'craft.leafPrint.5',
      audioPrompt: 'Make more prints with other colors. Orange, pink, any color you like!',
      animation: 'bounce',
    },
    {
      id: 'photo',
      order: 5,
      kind: 'PHOTO',
      instruction: 'Take a picture.',
      illustration: 'craft.leafPrint.6',
      audioPrompt: 'Take a picture of your leaf prints!',
      animation: 'bounce',
    },
    {
      id: 'save',
      order: 6,
      kind: 'SAVE',
      instruction: 'Save my leaf print.',
      illustration: 'craft.leafPrint.7',
      audioPrompt: 'Save your leaf print!',
      animation: 'sparkle',
      sound: 'celebrate',
    },
  ],
};
