import type { CraftTemplate } from '@/domain/craft/schema';

/** Paper Crown — cut, decorate, tape, wear. Grown-up helps with scissors. */
export const paperCrown: CraftTemplate = {
  id: 'crf_paper_crown',
  title: 'Paper Crown',
  noun: 'crown',
  description: 'Cut a zigzag strip of paper, decorate it with jewels, tape it into a crown.',
  icon: 'crown',
  illustration: 'craft.paperCrown.7',
  difficulty: 'EASY',
  estimatedMinutes: 15,
  materials: [
    'a long strip of yellow paper',
    'child-safe scissors',
    'crayons',
    'coloured paper',
    'tape',
  ],
  tags: ['paper', 'cutting', 'decorating', 'princess'],
  reward: { creativityPoints: 5, gardenItemId: 'flower' },
  completionAction: 'SAVE_PHOTO',
  steps: [
    {
      id: 'materials',
      order: 0,
      kind: 'INSTRUCTION',
      instruction: 'Get a long paper strip.',
      illustration: 'craft.paperCrown.1',
      audioPrompt: "Let's make a crown! Get a long strip of paper and your scissors.",
      animation: 'bounce',
    },
    {
      id: 'zigzag',
      order: 1,
      kind: 'INSTRUCTION',
      instruction: 'Cut a zigzag along the top.',
      illustration: 'craft.paperCrown.2',
      audioPrompt: 'Ask a grown-up to help you cut a zigzag along the top. Snip, snip!',
      animation: 'wiggle',
    },
    {
      id: 'draw',
      order: 2,
      kind: 'INSTRUCTION',
      instruction: 'Draw stars and hearts.',
      illustration: 'craft.paperCrown.3',
      audioPrompt: 'Draw stars and hearts on your crown with crayons.',
      animation: 'sparkle',
    },
    {
      id: 'jewels',
      order: 3,
      kind: 'INSTRUCTION',
      instruction: 'Stick on paper jewels.',
      illustration: 'craft.paperCrown.4',
      audioPrompt: 'Cut little paper circles and stick them on like jewels!',
      animation: 'grow',
    },
    {
      id: 'tape',
      order: 4,
      kind: 'INSTRUCTION',
      instruction: 'Bend it into a ring and tape it.',
      illustration: 'craft.paperCrown.5',
      audioPrompt: 'Bend the strip into a ring around your head and tape the ends together.',
      animation: 'bounce',
    },
    {
      id: 'photo',
      order: 5,
      kind: 'PHOTO',
      instruction: 'Take a picture.',
      illustration: 'craft.paperCrown.6',
      audioPrompt: 'Put on your crown and take a picture!',
      animation: 'bounce',
    },
    {
      id: 'save',
      order: 6,
      kind: 'SAVE',
      instruction: 'Save my crown.',
      illustration: 'craft.paperCrown.7',
      audioPrompt: 'Save your crown!',
      animation: 'sparkle',
      sound: 'celebrate',
    },
  ],
};
