import type { GradeWords } from '@/domain/generators/words';

export const grade2: GradeWords = {
  grade: 2,
  spelling: [
    { word: 'duck', hint: 'A bird that quacks and loves the water.' },
    { word: 'flag', hint: 'A piece of cloth that stands for a country.' },
    { word: 'seed', hint: 'A tiny thing that grows into a plant.' },
    { word: 'sand', hint: 'Tiny grains found on a beach or in a desert.' },
    { word: 'wave', hint: 'Water that moves up and down in the sea.' },
    { word: 'gate', hint: 'A door in a fence or wall.' },
    { word: 'lamb', hint: 'A young sheep with soft fluffy wool.' },
    { word: 'nail', hint: 'A thin metal pin used to hold wood together.' },
    { word: 'path', hint: 'A narrow trail you walk along.' },
    { word: 'gift', icon: 'gift', hint: 'A present you give to someone you love.' },
    { word: 'apple', icon: 'apple', hint: 'A round crunchy fruit that can be red or green.' },
    { word: 'house', icon: 'house', hint: 'A building where a family lives.' },
    { word: 'chair', icon: 'chair', hint: 'A seat with four legs and a back.' },
    { word: 'shell', icon: 'shell', hint: 'The hard outer covering of a sea animal.' },
    { word: 'heart', icon: 'heart', hint: 'A shape that means love.' },
    { word: 'crown', icon: 'crown', hint: 'A golden ring worn on the head of a king.' },
    { word: 'cloud', icon: 'cloud', hint: 'A fluffy white shape made of water in the sky.' },
    { word: 'spoon', icon: 'spoon', hint: 'A tool with a bowl shape used for eating.' },
    { word: 'shirt', icon: 'shirt', hint: 'A piece of clothing worn on the upper body.' },
    { word: 'mouth', icon: 'mouth', hint: 'The part of your face you use to talk and eat.' },
    { word: 'happy', hint: 'Feeling full of joy and smiles.' },
    { word: 'water', hint: 'A clear liquid we drink to stay healthy.' },
    { word: 'light', hint: 'Brightness that lets us see things clearly.' },
    { word: 'tiger', hint: 'A large wild cat with orange and black stripes.' },
    { word: 'smile', hint: 'To curve your mouth upward when you are happy.' },
    { word: 'dance', hint: 'To move your body to music.' },
    { word: 'clock', hint: 'A device that shows what time it is.' },
    { word: 'plant', hint: 'A living thing that grows from soil and needs water.' },
    { word: 'river', hint: 'A long flow of fresh water moving across the land.' },
    { word: 'sugar', hint: 'A sweet white powder used in cooking.' },
  ],
  sentences: [
    'The duck can swim.',
    'She wears a clean shirt.',
    'I got a lovely gift.',
    'The clock ticks fast.',
    'We plant seeds in soil.',
    'The tiger is very big.',
    'We dance with great joy.',
    'A shell rests in sand.',
    'She gives a warm smile.',
    'Lola tells us a story.',
    'The path leads to water.',
    'Sugar makes food taste sweet.',
  ],
  synonyms: [
    { word: 'happy', match: 'glad', others: ['sad', 'tired', 'cold'] },
    { word: 'big', match: 'large', others: ['tiny', 'round', 'dark'] },
    { word: 'fast', match: 'quick', others: ['slow', 'heavy', 'long'] },
    { word: 'small', match: 'little', others: ['huge', 'dark', 'wet'] },
    { word: 'cold', match: 'chilly', others: ['hot', 'warm', 'dry'] },
    { word: 'bright', match: 'shiny', others: ['dark', 'heavy', 'rough'] },
  ],
  antonyms: [
    { word: 'happy', match: 'sad', others: ['nice', 'cool', 'soft'] },
    { word: 'big', match: 'small', others: ['round', 'long', 'flat'] },
    { word: 'fast', match: 'slow', others: ['brave', 'clean', 'old'] },
    { word: 'day', match: 'night', others: ['noon', 'dawn', 'dusk'] },
    { word: 'hot', match: 'cold', others: ['wet', 'tall', 'round'] },
    { word: 'light', match: 'dark', others: ['heavy', 'sweet', 'flat'] },
  ],
  partsOfSpeech: [
    { word: 'rain', pos: 'noun', sentence: 'The rain is very cold.' },
    { word: 'moon', pos: 'noun', sentence: 'The moon shines at night.' },
    { word: 'book', pos: 'noun', sentence: 'She reads a good book.' },
    { word: 'tiger', pos: 'noun', sentence: 'The tiger is very big.' },
    { word: 'apple', pos: 'noun', sentence: 'The apple is bright red.' },
    { word: 'dance', pos: 'verb', sentence: 'The kids dance together.' },
    { word: 'smile', pos: 'verb', sentence: 'She can smile nicely.' },
    { word: 'plant', pos: 'verb', sentence: 'We plant the seeds.' },
  ],
};
