import type { GradeWords } from '@/domain/generators/words';

export const grade3: GradeWords = {
  grade: 3,
  spelling: [
    { word: 'brave', hint: 'Ready to face danger without fear.' },
    { word: 'clean', hint: 'Free from dirt or mess.' },
    { word: 'dream', hint: 'Pictures or thoughts that come while you sleep.' },
    { word: 'earth', hint: 'The planet where we all live together.' },
    { word: 'flame', hint: 'The glowing light produced by a fire.' },
    { word: 'greet', hint: 'To say hello to someone in a kind way.' },
    { word: 'storm', hint: 'Heavy rain and strong winds together.' },
    { word: 'juice', hint: 'A drink made from squeezed fruits.' },
    { word: 'laugh', hint: 'To make a happy sound when something is funny.' },
    { word: 'magic', hint: 'Something that seems impossible but happens anyway.' },
    { word: 'noble', hint: 'Having good moral qualities and being kind.' },
    { word: 'ocean', hint: 'A very large body of salt water.' },
    { word: 'party', hint: 'A fun gathering of friends to celebrate.' },
    { word: 'quiet', hint: 'Making very little or no noise.' },
    { word: 'reach', hint: 'To stretch out to touch or get something.' },
    { word: 'shout', hint: 'To speak very loudly.' },
    { word: 'table', hint: 'A flat surface on legs used for eating or working.' },
    { word: 'visit', hint: 'To go to see a person or a place.' },
    { word: 'watch', hint: 'To look at something carefully.' },
    { word: 'youth', hint: 'The time of life when you are young.' },
    { word: 'afraid', hint: 'Feeling fear or worry about something.' },
    { word: 'banana', hint: 'A long curved yellow fruit that monkeys love.' },
    { word: 'candle', hint: 'A stick of wax with a wick that burns to give light.' },
    { word: 'danger', hint: 'A situation that could cause harm or injury.' },
    { word: 'figure', hint: 'The shape or outline of a person or object.' },
    { word: 'garden', hint: 'A place where flowers and vegetables are grown.' },
    { word: 'health', hint: 'The state of being well and feeling strong.' },
    { word: 'joyful', hint: 'Feeling or showing great happiness.' },
    { word: 'nature', hint: 'The plants animals rivers and hills around us.' },
    { word: 'market', hint: 'A place where people buy and sell goods.' },
  ],
  sentences: [
    'The cat eats the fish.',
    'We plant mango trees here.',
    'The brave boy climbs fast.',
    'She drinks juice every day.',
    'The market is very busy.',
    'A candle gives us light.',
    'I dream of the ocean.',
    'The garden looks very green.',
    'They explore the big forest.',
    'Health is our true treasure.',
    'The party was full of joy.',
    'We greet lola at home.',
  ],
  synonyms: [
    { word: 'brave', match: 'bold', others: ['timid', 'quiet', 'slow'] },
    { word: 'happy', match: 'joyful', others: ['gloomy', 'tired', 'rough'] },
    { word: 'quick', match: 'swift', others: ['sluggish', 'heavy', 'loud'] },
    { word: 'begin', match: 'start', others: ['finish', 'rest', 'sleep'] },
    { word: 'angry', match: 'upset', others: ['happy', 'calm', 'gentle'] },
    { word: 'smart', match: 'clever', others: ['foolish', 'lazy', 'weak'] },
    { word: 'large', match: 'huge', others: ['tiny', 'soft', 'light'] },
    { word: 'cold', match: 'chilly', others: ['warm', 'bright', 'loud'] },
    { word: 'shout', match: 'yell', others: ['whisper', 'clap', 'dance'] },
    { word: 'tired', match: 'weary', others: ['rested', 'fresh', 'keen'] },
    { word: 'near', match: 'close', others: ['far', 'distant', 'wide'] },
    { word: 'pretty', match: 'lovely', others: ['ugly', 'dull', 'rough'] },
  ],
  antonyms: [
    { word: 'brave', match: 'timid', others: ['bold', 'strong', 'smart'] },
    { word: 'day', match: 'night', others: ['noon', 'dawn', 'evening'] },
    { word: 'early', match: 'late', others: ['soon', 'fast', 'near'] },
    { word: 'laugh', match: 'cry', others: ['smile', 'grin', 'shout'] },
    { word: 'clean', match: 'dirty', others: ['fresh', 'bright', 'neat'] },
    { word: 'hot', match: 'cold', others: ['warm', 'mild', 'cool'] },
    { word: 'start', match: 'finish', others: ['begin', 'enter', 'open'] },
    { word: 'quiet', match: 'loud', others: ['still', 'calm', 'soft'] },
    { word: 'young', match: 'old', others: ['small', 'fresh', 'green'] },
    { word: 'happy', match: 'sad', others: ['glad', 'joyful', 'merry'] },
    { word: 'wide', match: 'narrow', others: ['broad', 'long', 'deep'] },
    { word: 'hard', match: 'soft', others: ['firm', 'rigid', 'tough'] },
  ],
  partsOfSpeech: [
    { word: 'ocean', pos: 'noun', sentence: 'The ocean is very wide.' },
    { word: 'garden', pos: 'noun', sentence: 'Our garden has many flowers.' },
    { word: 'market', pos: 'noun', sentence: 'We buy fruit at the market.' },
    { word: 'candle', pos: 'noun', sentence: 'A candle glows in the dark.' },
    { word: 'dream', pos: 'verb', sentence: 'I dream of flying very high.' },
    { word: 'reach', pos: 'verb', sentence: 'She can reach the top shelf.' },
    { word: 'shout', pos: 'verb', sentence: 'Please do not shout inside.' },
    { word: 'visit', pos: 'verb', sentence: 'We visit our lola every week.' },
    { word: 'brave', pos: 'adjective', sentence: 'The brave knight crossed the river.' },
    { word: 'quiet', pos: 'adjective', sentence: 'The library must stay quiet.' },
    { word: 'clean', pos: 'adjective', sentence: 'Always keep your room clean.' },
    { word: 'joyful', pos: 'adjective', sentence: 'The children were joyful at the fiesta.' },
  ],
};
