import type { GradeWords } from '@/domain/generators/words';

export const grade5: GradeWords = {
  grade: 5,
  spelling: [
    { word: 'island', hint: 'A piece of land surrounded by water.' },
    { word: 'volcano', hint: 'A mountain that can shoot out hot lava.' },
    { word: 'pattern', hint: 'A repeated design or set of colors and shapes.' },
    { word: 'student', hint: 'A person who studies at school.' },
    { word: 'similar', hint: 'Almost the same but not exactly.' },
    { word: 'between', hint: 'In the middle of two things.' },
    { word: 'correct', hint: 'True or right with no mistakes.' },
    { word: 'believe', hint: 'To feel sure that something is true.' },
    { word: 'support', hint: 'To help someone or hold something up.' },
    { word: 'science', hint: 'The study of the natural world through experiments.' },
    { word: 'message', hint: 'Words spoken or written to tell someone something.' },
    { word: 'improve', hint: 'To become or make something better.' },
    { word: 'include', hint: 'To have something as part of a group.' },
    { word: 'history', hint: 'The record of things that happened in the past.' },
    { word: 'country', hint: 'A land with its own government and people.' },
    { word: 'develop', hint: 'To grow or build up over time.' },
    { word: 'protect', hint: 'To keep something safe from harm.' },
    { word: 'culture', hint: 'The traditions and ways of life of a people.' },
    { word: 'society', hint: 'A group of people living together in a community.' },
    { word: 'produce', hint: 'To make or create something.' },
    { word: 'prevent', hint: 'To stop something from happening.' },
    { word: 'program', hint: 'A plan or set of activities with a purpose.' },
    { word: 'discover', hint: 'To find or learn something for the first time.' },
    { word: 'mountain', hint: 'A very high area of land rising from the earth.' },
    { word: 'medicine', hint: 'A substance used to treat illness or pain.' },
    { word: 'describe', hint: 'To give details about what something is like.' },
    { word: 'exercise', hint: 'Physical activity that keeps the body healthy.' },
    { word: 'together', hint: 'With each other at the same time or place.' },
    { word: 'document', hint: 'A written or printed paper with important information.' },
    { word: 'barangay', hint: 'The smallest unit of government in the Philippines.' },
  ],
  sentences: [
    'The barangay fiesta is next week.',
    'Our country has many beautiful islands.',
    'Students must study science every day.',
    'The volcano has not erupted in years.',
    'We protect the environment for the future.',
    'I believe in working hard every day.',
    'History helps us learn from the past.',
    'The mountain air feels fresh and cool.',
    'Our culture is rich with Filipino music.',
    'They discovered a new medicine for the sick.',
    'The message from lola made us smile.',
    'We must support each other as a community.',
  ],
  synonyms: [
    { word: 'discover', match: 'uncover', others: ['lose', 'forget', 'ignore'] },
    { word: 'support', match: 'assist', others: ['hinder', 'block', 'oppose'] },
    { word: 'believe', match: 'trust', others: ['doubt', 'deny', 'reject'] },
    { word: 'improve', match: 'enhance', others: ['worsen', 'reduce', 'ruin'] },
    { word: 'protect', match: 'guard', others: ['expose', 'harm', 'abandon'] },
    { word: 'describe', match: 'explain', others: ['confuse', 'hide', 'deny'] },
    { word: 'similar', match: 'alike', others: ['different', 'opposite', 'unique'] },
    { word: 'ancient', match: 'old', others: ['modern', 'fresh', 'recent'] },
    { word: 'enormous', match: 'huge', others: ['tiny', 'slim', 'thin'] },
    { word: 'brave', match: 'courageous', others: ['fearful', 'timid', 'weak'] },
    { word: 'clever', match: 'intelligent', others: ['foolish', 'dull', 'careless'] },
    { word: 'reply', match: 'respond', others: ['question', 'ignore', 'avoid'] },
    { word: 'begin', match: 'commence', others: ['finish', 'stop', 'prevent'] },
    { word: 'allow', match: 'permit', others: ['forbid', 'refuse', 'block'] },
    { word: 'correct', match: 'accurate', others: ['wrong', 'false', 'mistaken'] },
  ],
  antonyms: [
    { word: 'discover', match: 'conceal', others: ['find', 'seek', 'uncover'] },
    { word: 'improve', match: 'worsen', others: ['fix', 'build', 'change'] },
    { word: 'protect', match: 'expose', others: ['guard', 'shield', 'defend'] },
    { word: 'include', match: 'exclude', others: ['add', 'join', 'count'] },
    { word: 'correct', match: 'incorrect', others: ['right', 'exact', 'proper'] },
    { word: 'support', match: 'oppose', others: ['help', 'aid', 'back'] },
    { word: 'believe', match: 'doubt', others: ['trust', 'think', 'sense'] },
    { word: 'develop', match: 'decline', others: ['grow', 'build', 'rise'] },
    { word: 'modern', match: 'ancient', others: ['current', 'recent', 'fresh'] },
    { word: 'similar', match: 'different', others: ['alike', 'same', 'close'] },
    { word: 'courage', match: 'cowardice', others: ['bravery', 'strength', 'valor'] },
    { word: 'produce', match: 'consume', others: ['make', 'create', 'build'] },
    { word: 'prevent', match: 'allow', others: ['stop', 'block', 'avoid'] },
    { word: 'society', match: 'isolation', others: ['community', 'group', 'people'] },
    { word: 'success', match: 'failure', others: ['victory', 'triumph', 'win'] },
  ],
  partsOfSpeech: [
    { word: 'island', pos: 'noun', sentence: 'The island is surrounded by the sea.' },
    { word: 'volcano', pos: 'noun', sentence: 'The volcano erupted after many years.' },
    { word: 'mountain', pos: 'noun', sentence: 'The mountain is covered with thick trees.' },
    { word: 'barangay', pos: 'noun', sentence: 'Our barangay has a new clean park.' },
    { word: 'discover', pos: 'verb', sentence: 'Scientists discover new medicines every year.' },
    { word: 'improve', pos: 'verb', sentence: 'We must improve our study habits daily.' },
    { word: 'protect', pos: 'verb', sentence: 'We must protect the environment we share.' },
    { word: 'develop', pos: 'verb', sentence: 'Cities develop quickly as more people arrive.' },
    { word: 'similar', pos: 'adjective', sentence: 'The two pictures look very similar to me.' },
    { word: 'correct', pos: 'adjective', sentence: 'She gave the correct answer in class.' },
    { word: 'ancient', pos: 'adjective', sentence: 'The ancient temple was tall and grand.' },
    { word: 'powerful', pos: 'adjective', sentence: 'The powerful typhoon moved across the sea.' },
    { word: 'deeply', pos: 'adverb', sentence: 'He cared deeply about the people around him.' },
    { word: 'clearly', pos: 'adverb', sentence: 'She spoke clearly so everyone could hear.' },
    { word: 'they', pos: 'pronoun', sentence: 'They visited the barangay park today.' },
    { word: 'we', pos: 'pronoun', sentence: 'We must take care of our oceans.' },
    { word: 'above', pos: 'preposition', sentence: 'The kite flew above the tall trees.' },
    {
      word: 'between',
      pos: 'preposition',
      sentence: 'The river flows between two tall mountains.',
    },
  ],
};
