import type { GradeWords } from '@/domain/generators/words';

export const grade1: GradeWords = {
  grade: 1,
  spelling: [
    { word: 'cat', icon: 'cat', hint: 'A small furry pet that says meow.' },
    { word: 'dog', icon: 'dog', hint: 'A friendly pet that loves to play.' },
    { word: 'sun', icon: 'sun', hint: 'The bright star that warms our day.' },
    { word: 'hat', icon: 'hat', hint: 'Something you wear on your head.' },
    { word: 'cup', icon: 'cup', hint: 'A small container for drinks.' },
    { word: 'pig', icon: 'pig', hint: 'A pink farm animal that says oink.' },
    { word: 'fish', icon: 'fish', hint: 'An animal that swims in the water.' },
    { word: 'bird', icon: 'bird', hint: 'An animal with wings that can fly.' },
    { word: 'ball', icon: 'ball', hint: 'A round toy you can throw or kick.' },
    { word: 'boat', icon: 'boat', hint: 'A vehicle that floats on water.' },
    { word: 'tree', icon: 'tree', hint: 'A tall plant with branches and leaves.' },
    { word: 'hand', icon: 'hand', hint: 'The part of your body with five fingers.' },
    { word: 'star', icon: 'star', hint: 'A bright light you see in the night sky.' },
    { word: 'moon', icon: 'moon', hint: 'The round light that shines at night.' },
    { word: 'rice', icon: 'rice', hint: 'A white grain that Filipinos eat every day.' },
    { word: 'frog', icon: 'frog', hint: 'A green animal that jumps and says ribbit.' },
    { word: 'bee', icon: 'bee', hint: 'A flying insect that makes sweet honey.' },
    { word: 'eye', icon: 'eye', hint: 'The part of your face you use to see.' },
    { word: 'ear', icon: 'ear', hint: 'The part of your head you use to hear.' },
    { word: 'nose', icon: 'nose', hint: 'The part of your face you use to smell.' },
    { word: 'foot', icon: 'foot', hint: 'The part at the bottom of your leg.' },
    { word: 'leaf', icon: 'leaf', hint: 'The flat green part of a plant.' },
    { word: 'book', icon: 'book', hint: 'Pages with words and pictures to read.' },
    { word: 'rock', icon: 'rock', hint: 'A hard piece of stone from the ground.' },
    { word: 'rain', icon: 'rain', hint: 'Water that falls from clouds in the sky.' },
    { word: 'mango', icon: 'mango', hint: 'A sweet yellow fruit from the Philippines.' },
    { word: 'crab', icon: 'crab', hint: 'A sea animal with claws and a hard shell.' },
    { word: 'run', hint: 'To move quickly on your feet.' },
    { word: 'big', hint: 'Large in size.' },
    { word: 'red', hint: 'A bright color like a ripe tomato.' },
  ],
  sentences: [
    'The cat is big.',
    'I see the sun.',
    'The dog runs fast.',
    'She has a hat.',
    'The fish can swim.',
    'I love to run.',
    'The bird sings well.',
    'He is a boy.',
    'The frog can jump.',
    'The star shines bright.',
    'The rain is cold.',
    'The ball rolls down.',
  ],
  synonyms: [
    { word: 'big', match: 'large', others: ['small', 'round', 'fast'] },
    { word: 'happy', match: 'glad', others: ['sad', 'dark', 'cold'] },
    { word: 'fast', match: 'quick', others: ['slow', 'tall', 'wet'] },
    { word: 'small', match: 'tiny', others: ['huge', 'loud', 'hard'] },
    { word: 'look', match: 'see', others: ['run', 'sit', 'eat'] },
    { word: 'shut', match: 'close', others: ['open', 'jump', 'sing'] },
  ],
  antonyms: [
    { word: 'big', match: 'small', others: ['round', 'fast', 'tall'] },
    { word: 'hot', match: 'cold', others: ['wet', 'hard', 'loud'] },
    { word: 'up', match: 'down', others: ['stop', 'left', 'spin'] },
    { word: 'day', match: 'night', others: ['rain', 'noon', 'wind'] },
    { word: 'fast', match: 'slow', others: ['old', 'loud', 'wide'] },
    { word: 'yes', match: 'no', others: ['good', 'stop', 'here'] },
  ],
  partsOfSpeech: [
    { word: 'cat', pos: 'noun', sentence: 'The cat is cute.' },
    { word: 'dog', pos: 'noun', sentence: 'The dog is big.' },
    { word: 'sun', pos: 'noun', sentence: 'The sun is hot.' },
    { word: 'hat', pos: 'noun', sentence: 'My hat is red.' },
    { word: 'fish', pos: 'noun', sentence: 'The fish swims.' },
    { word: 'bird', pos: 'noun', sentence: 'The bird sings.' },
    { word: 'run', pos: 'verb', sentence: 'The kids run fast.' },
    { word: 'jump', pos: 'verb', sentence: 'The frog can jump.' },
  ],
};
