import type { GradeWords } from '@/domain/generators/words';

export const grade6: GradeWords = {
  grade: 6,
  spelling: [
    { word: 'absolute', hint: 'Complete and total with nothing left out.' },
    { word: 'balanced', hint: 'Having equal weight or fairness on all sides.' },
    { word: 'chemical', hint: 'Relating to substances and how they react.' },
    { word: 'conclude', hint: 'To bring something to an end or reach a decision.' },
    { word: 'creative', hint: 'Using imagination to make new or original things.' },
    { word: 'dedicate', hint: 'To give time and effort fully to something.' },
    { word: 'evaluate', hint: 'To judge or assess the value of something.' },
    { word: 'generate', hint: 'To produce or bring something into existence.' },
    { word: 'humanity', hint: 'All people in the world thought of as a group.' },
    { word: 'industry', hint: 'The work of making goods or providing services.' },
    { word: 'community', hint: 'A group of people living in the same area.' },
    { word: 'democracy', hint: 'A system of government chosen by the people.' },
    { word: 'education', hint: 'The process of learning through school and study.' },
    { word: 'pollution', hint: 'Harmful substances that damage the environment.' },
    { word: 'tradition', hint: 'A custom or belief passed down through generations.' },
    { word: 'celebrate', hint: 'To do something enjoyable for a special occasion.' },
    { word: 'character', hint: 'The qualities that make a person who they are.' },
    { word: 'introduce', hint: 'To present something or someone for the first time.' },
    { word: 'necessary', hint: 'Something that must be done or that is needed.' },
    { word: 'recognize', hint: 'To identify or know something from memory.' },
    { word: 'sacrifice', hint: 'To give up something important for another reason.' },
    { word: 'volunteer', hint: 'A person who offers to help without being paid.' },
    { word: 'curiosity', hint: 'A strong desire to know or learn something new.' },
    { word: 'structure', hint: 'The way parts are arranged or organized together.' },
    { word: 'magnitude', hint: 'The size or importance of something.' },
    { word: 'government', hint: 'The group of people who run a country or region.' },
    { word: 'revolution', hint: 'A great change in the way things are done.' },
    { word: 'technology', hint: 'Tools and systems created using science.' },
    { word: 'environment', hint: 'The natural world of land water and living things.' },
    { word: 'celebration', hint: 'A joyful event held to mark something special.' },
  ],
  sentences: [
    'The government must protect the environment.',
    'Our community celebrates the fiesta together.',
    'Education is the key to a bright future.',
    'Technology helps us connect with the world.',
    'Democracy means every voice must be heard.',
    'Pollution is a very serious problem today.',
    'We must recognize the beauty of tradition.',
    'Volunteers help make our barangay very clean.',
    'Revolution changed the course of our history.',
    'Curiosity helps scientists discover great new things.',
    'Our character is shown in how we act.',
    'The celebration brought joy to our whole street.',
  ],
  synonyms: [
    { word: 'environment', match: 'surroundings', others: ['weather', 'darkness', 'silence'] },
    { word: 'government', match: 'authority', others: ['family', 'company', 'school'] },
    { word: 'democracy', match: 'republic', others: ['monarchy', 'tyranny', 'chaos'] },
    { word: 'tradition', match: 'custom', others: ['invention', 'science', 'fiction'] },
    { word: 'pollution', match: 'contamination', others: ['cleanliness', 'beauty', 'growth'] },
    { word: 'volunteer', match: 'helper', others: ['bystander', 'opponent', 'critic'] },
    { word: 'recognize', match: 'identify', others: ['ignore', 'forget', 'confuse'] },
    { word: 'sacrifice', match: 'offering', others: ['reward', 'benefit', 'profit'] },
    { word: 'celebrate', match: 'commemorate', others: ['ignore', 'forget', 'abandon'] },
    { word: 'curiosity', match: 'wonder', others: ['boredom', 'silence', 'neglect'] },
    { word: 'structure', match: 'framework', others: ['chaos', 'mess', 'disorder'] },
    { word: 'necessary', match: 'essential', others: ['optional', 'useless', 'trivial'] },
    { word: 'introduce', match: 'present', others: ['remove', 'hide', 'destroy'] },
    { word: 'determine', match: 'decide', others: ['ignore', 'avoid', 'delay'] },
    { word: 'influence', match: 'impact', others: ['weakness', 'failure', 'ignorance'] },
  ],
  antonyms: [
    { word: 'pollution', match: 'purity', others: ['smog', 'waste', 'filth'] },
    { word: 'democracy', match: 'dictatorship', others: ['republic', 'freedom', 'voting'] },
    { word: 'tradition', match: 'innovation', others: ['custom', 'culture', 'ritual'] },
    { word: 'volunteer', match: 'bystander', others: ['helper', 'giver', 'worker'] },
    { word: 'necessary', match: 'optional', others: ['needed', 'vital', 'crucial'] },
    { word: 'creative', match: 'unimaginative', others: ['artistic', 'clever', 'unique'] },
    { word: 'introduce', match: 'conclude', others: ['present', 'begin', 'open'] },
    { word: 'structure', match: 'disorder', others: ['system', 'pattern', 'form'] },
    { word: 'celebrate', match: 'mourn', others: ['enjoy', 'cheer', 'feast'] },
    { word: 'sacrifice', match: 'selfishness', others: ['offering', 'giving', 'devotion'] },
    { word: 'curiosity', match: 'apathy', others: ['wonder', 'interest', 'zeal'] },
    { word: 'absolute', match: 'partial', others: ['complete', 'total', 'whole'] },
    { word: 'generate', match: 'consume', others: ['produce', 'create', 'make'] },
    { word: 'influence', match: 'weakness', others: ['power', 'impact', 'effect'] },
    { word: 'recognize', match: 'ignore', others: ['see', 'notice', 'know'] },
  ],
  partsOfSpeech: [
    { word: 'community', pos: 'noun', sentence: 'Our community gathers to help each other.' },
    {
      word: 'government',
      pos: 'noun',
      sentence: 'The government serves the people of the nation.',
    },
    {
      word: 'tradition',
      pos: 'noun',
      sentence: 'Our tradition is passed down from each generation.',
    },
    { word: 'structure', pos: 'noun', sentence: 'The structure of the bridge is very strong.' },
    {
      word: 'celebrate',
      pos: 'verb',
      sentence: 'Filipinos celebrate fiestas with great joy and food.',
    },
    { word: 'generate', pos: 'verb', sentence: 'Solar panels generate clean energy from the sun.' },
    { word: 'introduce', pos: 'verb', sentence: 'Let me introduce you to my good friend.' },
    { word: 'recognize', pos: 'verb', sentence: 'We must recognize the rights of every person.' },
    {
      word: 'absolute',
      pos: 'adjective',
      sentence: 'She showed absolute dedication to her studies.',
    },
    {
      word: 'creative',
      pos: 'adjective',
      sentence: 'The creative student made a beautiful art piece.',
    },
    {
      word: 'necessary',
      pos: 'adjective',
      sentence: 'Clean water is necessary for every living thing.',
    },
    {
      word: 'essential',
      pos: 'adjective',
      sentence: 'Respect is essential in every good friendship.',
    },
    {
      word: 'greatly',
      pos: 'adverb',
      sentence: 'The team greatly improved their performance this year.',
    },
    { word: 'firmly', pos: 'adverb', sentence: 'She firmly believed in the power of education.' },
    {
      word: 'everyone',
      pos: 'pronoun',
      sentence: 'Everyone joined the barangay cleanup drive today.',
    },
    { word: 'someone', pos: 'pronoun', sentence: 'Someone left a bag on the classroom floor.' },
    {
      word: 'throughout',
      pos: 'preposition',
      sentence: 'Trees were planted throughout the whole barangay.',
    },
    {
      word: 'beyond',
      pos: 'preposition',
      sentence: 'The view beyond the mountain was breathtaking.',
    },
  ],
};
