import type { GradeWords } from '@/domain/generators/words';

export const grade4: GradeWords = {
  grade: 4,
  spelling: [
    { word: 'simple', hint: 'Easy to understand or do.' },
    { word: 'follow', hint: 'To go or come after someone.' },
    { word: 'ground', hint: 'The solid surface of the earth we walk on.' },
    { word: 'window', hint: 'An opening in a wall covered with glass.' },
    { word: 'happen', hint: 'To take place or occur.' },
    { word: 'change', hint: 'To become different or make something different.' },
    { word: 'people', hint: 'Men women and children who live in a place.' },
    { word: 'always', hint: 'At all times without exception.' },
    { word: 'around', hint: 'On all sides or in a circle.' },
    { word: 'proper', hint: 'Correct or suitable for a situation.' },
    { word: 'ancient', hint: 'Very old belonging to a long time ago.' },
    { word: 'breathe', hint: 'To take air in and out of your lungs.' },
    { word: 'captain', hint: 'The leader of a ship team or group.' },
    { word: 'disease', hint: 'An illness that affects the body or mind.' },
    { word: 'freedom', hint: 'The right to do or say what you choose.' },
    { word: 'harvest', hint: 'To gather crops that are ready to be picked.' },
    { word: 'imagine', hint: 'To form a picture or idea in your mind.' },
    { word: 'justice', hint: 'Fairness and treating people as they deserve.' },
    { word: 'library', hint: 'A place where books and information are kept.' },
    { word: 'mention', hint: 'To speak or write about something briefly.' },
    { word: 'natural', hint: 'Made by nature and not by people.' },
    { word: 'opinion', hint: 'What you think or believe about something.' },
    { word: 'respect', hint: 'To treat someone with care and consideration.' },
    { word: 'success', hint: 'Reaching a goal or doing something well.' },
    { word: 'teacher', hint: 'A person who helps others learn new things.' },
    { word: 'village', hint: 'A small community smaller than a town.' },
    { word: 'courage', hint: 'The strength to do something even when afraid.' },
    { word: 'explore', hint: 'To travel and discover new places.' },
    { word: 'backbone', hint: 'The column of bones running down your back.' },
    { word: 'calendar', hint: 'A chart that shows all the days of a year.' },
  ],
  sentences: [
    'The teacher writes on the blackboard.',
    'Our village has a big library.',
    'She has the courage to speak.',
    'We must respect our lola always.',
    'The harvest festival was full of joy.',
    'I imagine flying over the island.',
    'Justice means being fair to everyone.',
    'The weather is warm during summer.',
    'People change when they grow older.',
    'The captain steered the boat safely.',
    'Freedom is a gift we must protect.',
    'A calendar helps us plan our days.',
  ],
  synonyms: [
    { word: 'ancient', match: 'old', others: ['new', 'young', 'fresh'] },
    { word: 'brave', match: 'courageous', others: ['timid', 'weak', 'lazy'] },
    { word: 'happy', match: 'joyful', others: ['gloomy', 'angry', 'tired'] },
    { word: 'clever', match: 'smart', others: ['foolish', 'dull', 'weak'] },
    { word: 'huge', match: 'enormous', others: ['tiny', 'slim', 'short'] },
    { word: 'sad', match: 'sorrowful', others: ['happy', 'merry', 'bright'] },
    { word: 'quick', match: 'swift', others: ['slow', 'lazy', 'heavy'] },
    { word: 'beautiful', match: 'lovely', others: ['ugly', 'dull', 'plain'] },
    { word: 'difficult', match: 'hard', others: ['easy', 'simple', 'light'] },
    { word: 'shout', match: 'yell', others: ['whisper', 'sing', 'hum'] },
    { word: 'friend', match: 'buddy', others: ['enemy', 'rival', 'foe'] },
    { word: 'begin', match: 'commence', others: ['finish', 'stop', 'end'] },
    { word: 'hot', match: 'scorching', others: ['cold', 'cool', 'mild'] },
    { word: 'narrow', match: 'thin', others: ['wide', 'broad', 'thick'] },
    { word: 'rich', match: 'wealthy', others: ['poor', 'broke', 'needy'] },
  ],
  antonyms: [
    { word: 'ancient', match: 'modern', others: ['old', 'broken', 'dull'] },
    { word: 'brave', match: 'timid', others: ['bold', 'strong', 'proud'] },
    { word: 'succeed', match: 'fail', others: ['try', 'work', 'earn'] },
    { word: 'freedom', match: 'captivity', others: ['liberty', 'peace', 'safety'] },
    { word: 'natural', match: 'artificial', others: ['organic', 'raw', 'plain'] },
    { word: 'gather', match: 'scatter', others: ['collect', 'pick', 'bunch'] },
    { word: 'expand', match: 'shrink', others: ['grow', 'rise', 'spread'] },
    { word: 'honest', match: 'dishonest', others: ['truthful', 'sincere', 'fair'] },
    { word: 'friend', match: 'enemy', others: ['buddy', 'partner', 'ally'] },
    { word: 'accept', match: 'reject', others: ['receive', 'welcome', 'take'] },
    { word: 'victory', match: 'defeat', others: ['win', 'triumph', 'prize'] },
    { word: 'wisdom', match: 'foolishness', others: ['knowledge', 'insight', 'sense'] },
    { word: 'rough', match: 'smooth', others: ['hard', 'rigid', 'bumpy'] },
    { word: 'remember', match: 'forget', others: ['recall', 'review', 'learn'] },
    { word: 'generous', match: 'selfish', others: ['kind', 'giving', 'gentle'] },
  ],
  partsOfSpeech: [
    { word: 'village', pos: 'noun', sentence: 'Our village has a big market.' },
    { word: 'library', pos: 'noun', sentence: 'The library has many good books.' },
    { word: 'harvest', pos: 'noun', sentence: 'The harvest was very plentiful.' },
    { word: 'captain', pos: 'noun', sentence: 'The captain sailed the big ship.' },
    { word: 'explore', pos: 'verb', sentence: 'We love to explore the forest.' },
    { word: 'imagine', pos: 'verb', sentence: 'I can imagine a better world.' },
    { word: 'breathe', pos: 'verb', sentence: 'Always breathe in clean fresh air.' },
    { word: 'mention', pos: 'verb', sentence: 'Did you mention the new plan?' },
    { word: 'ancient', pos: 'adjective', sentence: 'The ancient ruins are very tall.' },
    { word: 'natural', pos: 'adjective', sentence: 'The river flows in a natural path.' },
    { word: 'proper', pos: 'adjective', sentence: 'Use proper words when you speak.' },
    { word: 'distant', pos: 'adjective', sentence: 'The distant mountains look very blue.' },
    { word: 'quickly', pos: 'adverb', sentence: 'She quickly finished all her work.' },
    { word: 'slowly', pos: 'adverb', sentence: 'The turtle walked very slowly home.' },
    { word: 'always', pos: 'adverb', sentence: 'We must always be very kind.' },
  ],
};
