#!/usr/bin/env node
/**
 * Runs after `expo export --platform web`. Makes the static `dist/` folder a proper
 * installable, offline-capable PWA on any static host:
 *
 *  1. 404.html = index.html so deep links (/home, /book/abc) resolve on GitHub Pages.
 *  2. Rewrites manifest.json paths for the configured base path (EXPO_PUBLIC_WEB_BASE).
 *  3. Generates sw.js: precaches every exported file (hashed JS chunks, WebP, MP3, icons)
 *     so the second launch is instant and the app works with no network — a tablet in
 *     the back seat of a car still opens Diamond Island. Cache name is derived from the
 *     file list, so every new deploy replaces the old cache cleanly.
 *
 * No analytics, no third-party requests, nothing leaves the device.
 */
import { createHash } from 'node:crypto';
import { promises as fs } from 'node:fs';
import path from 'node:path';

const dist = path.resolve(process.argv[2] ?? 'dist');
const base = (process.env.EXPO_PUBLIC_WEB_BASE ?? '').replace(/\/+$/, '');

async function walk(dir, prefix = '') {
  const out = [];
  for (const entry of await fs.readdir(dir, { withFileTypes: true })) {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) out.push(...(await walk(path.join(dir, entry.name), rel)));
    else out.push(rel);
  }
  return out;
}

const indexHtml = await fs.readFile(path.join(dist, 'index.html'), 'utf8');
await fs.writeFile(path.join(dist, '404.html'), indexHtml);

const manifestPath = path.join(dist, 'manifest.json');
const manifest = JSON.parse(await fs.readFile(manifestPath, 'utf8'));
manifest.start_url = `${base}/`;
manifest.scope = `${base}/`;
manifest.icons = manifest.icons.map((icon) => ({ ...icon, src: `${base}${icon.src}` }));
await fs.writeFile(manifestPath, JSON.stringify(manifest, null, 2));

const files = (await walk(dist))
  .filter((f) => !f.endsWith('.map') && f !== 'sw.js' && f !== '404.html' && !f.endsWith('.html'))
  .sort();
const routesHtml = (await walk(dist)).filter((f) => f.endsWith('.html') && f !== '404.html');
const precache = [`${base}/`, ...files.map((f) => `${base}/${f}`)];
// Version = hash of every precached file's CONTENT (not just names): unhashed files such
// as icons and the manifest must also invalidate the cache when they change.
const hash = createHash('sha1').update(indexHtml);
for (const f of files) hash.update(f).update(await fs.readFile(path.join(dist, f)));
const version = hash.digest('hex').slice(0, 12);

const sw = `/* PJ's Diamond World service worker — generated by scripts/postexport.mjs */
const CACHE = 'pjdw-${version}';
const BASE = ${JSON.stringify(base)};
const PRECACHE = ${JSON.stringify(precache)};
const INDEX = BASE + '/';

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // App shell: the exported HTML is identical for every route, so any navigation is
  // served from the cached index (network first so a new deploy is picked up online).
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(INDEX, copy));
          return response;
        })
        .catch(() => caches.match(INDEX)),
    );
    return;
  }

  // Content packs update between deploys: network first, cache as fallback.
  if (url.pathname.startsWith(BASE + '/content/')) {
    event.respondWith(
      fetch(request)
        .then((response) => {
          if (response.status === 200) {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request.url.split('?')[0], copy)).catch(() => {});
          }
          return response;
        })
        .catch(() => caches.match(request.url.split('?')[0]).then((c) => c || Response.error())),
    );
    return;
  }

  // Everything else is content-hashed or immutable per deploy: cache first.
  // Media elements ask for audio with a Range header; the Cache API never matches
  // those against the stored full file, so answer them ourselves with a 206 slice —
  // otherwise sound cues fail offline.
  const cachedResponse = request.headers.has('range')
    ? caches.match(request.url).then((full) => full && partial(request, full))
    : caches.match(request);
  event.respondWith(
    cachedResponse.then(
      (cached) =>
        cached ||
        fetch(request).then((response) => {
          if (response.status === 200) {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request, copy)).catch(() => {});
          }
          return response;
        }),
    ),
  );
});

async function partial(request, full) {
  const match = /bytes=(\\d*)-(\\d*)/.exec(request.headers.get('range') || '');
  const buffer = await full.arrayBuffer();
  const total = buffer.byteLength;
  if (!match) return new Response(buffer, { status: 200, headers: full.headers });
  const start = match[1] ? Number(match[1]) : 0;
  let end = match[2] ? Number(match[2]) : total - 1;
  if (start >= total) {
    return new Response(null, { status: 416, headers: { 'Content-Range': 'bytes */' + total } });
  }
  end = Math.min(end, total - 1);
  const slice = buffer.slice(start, end + 1);
  const headers = new Headers(full.headers);
  headers.set('Content-Range', 'bytes ' + start + '-' + end + '/' + total);
  headers.set('Content-Length', String(slice.byteLength));
  headers.set('Accept-Ranges', 'bytes');
  return new Response(slice, { status: 206, statusText: 'Partial Content', headers });
}
`;
await fs.writeFile(path.join(dist, 'sw.js'), sw);

const totalBytes = (
  await Promise.all(files.map((f) => fs.stat(path.join(dist, f)).then((s) => s.size)))
).reduce((a, b) => a + b, 0);
console.log(
  `postexport: base="${base || '/'}" · ${files.length} files precached (${(totalBytes / 1024 / 1024).toFixed(2)} MB) · ${routesHtml.length} routes · sw cache ${version}`,
);
